### PR TITLE
Add path prefix into the template file

### LINKED ISSUE #1355: Vault Prefix Property Not Utilized
After installing Vault 3.3.0, we set the [vault.path_prefix](https://github.com/concourse/concourse/blob/v3.3.0/jobs/atc/spec#L409-L412) in our deployment manifest, but the property does not seem to have any effect and we receive an error from atc indicating it is still looking at the default prefix of `/concourse`.

We also tried manually injecting `--vault-prefix`, as mentioned [here](https://concourse.ci/creds.html), into the generated `atc_ctl` startup script, and received this error:
`unknown flag 'vault-prefix'`

### PR DESCRIPTION
**Pull request by gondoi**
We modified the atc_ctl script manually and restarted with monit to validate this fix works as expected.

fixes #1355

Signed-off-by: Steve Katen <steve.katen@rackspace.com>

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@gondoi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/concourse&pullRequestId=1357)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/concourse&pullRequestId=1357) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by gondoi** [comment]
I would define this as an "Obvious Fix" and should be able to merge without signing the CLA. I can sign the CLA, but I first need to track down if I need to individual or corporate with my employer.

**Comment by pivotal-issuemaster** [comment]
@gondoi This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by gondoi** [comment]
What are the next steps for this to make it's way into a release?

**Pull request merged**
