### PR TITLE
add metrics for job scheduling, build starting, build tracking

### LINKED ISSUE #5121: Implement Prometheus metrics for new scheduler
Also clean up no-longer-used scheduling metrics like `SchedulingLoadVersionsDuration`

### PR DESCRIPTION
**Pull request by vito**
# Existing Issue

Fixes #5121.

# Why do we need this PR?

This PR replaces the no-longer-functional scheduling metrics from the old algorithm with basic counter metrics which are easier to support with Prometheus.

# Changes proposed in this pull request

Introduces four new metrics:

* `builds started`: a counter of builds which have been started
* `builds running`: a gauge of builds which are being tracked (i.e. ran)
* `jobs scheduled`: a counter of jobs which have been scheduled
* `jobs scheduling`: a gauge of jobs which are being scheduled

I fixed a few broken windows along the way:

* standardize metric values on `float64`
* remove the Riemann emitter and the OK/Warning/Critical state stuff
* rename `Meter` to `Counter`

# Contributor Checklist

- [ ] Unit tests
- [ ] Integration tests (if applicable)
- [ ] Updated documentation (located at https://github.com/concourse/docs)
- [ ] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)

# Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the [BOSH](https://github.com/concourse/concourse-bosh-release) 
      and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not displayed in the `--help` text).

### CODE REVIEW

**Comment by cirocosta** [comment]
```go
        checksVec := prometheus.NewHistogramVec(
                prometheus.HistogramOpts{
                        Namespace: "concourse",
                        Subsystem: "lidar",
                        Name:      "duration_seconds",
                        Help:      "Check time in seconds",
                        Buckets:   []float64{0.001, 0.05, 0.1, 0.5, 1, 60, 180, 360, 720, 1440, 2880},
                },
                []string{"scope_id", "status"},
        )
        prometheus.MustRegister(checksVec)

        checkEnqueueVec := prometheus.NewCounterVec(
                prometheus.CounterOpts{
                        Namespace: "concourse",
                        Subsystem: "lidar",
                        Name:      "check_enqueue",
                        Help:      "Counts the number of checks enqueued",
                },
                []string{"scope_id", "name"},
        )
        prometheus.MustRegister(checkEnqueueVec)
```

not related to this PR per-se, but thiiiiiiis is kinda scary - `scope_Id` there + all of the dimensions for the buckets on the first (histogram) will generate tons of timeseries

**Comment by vito** [comment]
@cirocosta Yeah that definitely looks like it'd be pretty hairy.

I wonder if we should just do checking metrics similar to the ones that I added: a counter for checks completed and a gauge for checks in-flight?

I don't really think that fine-grained check timing information is very useful compared to its cost. It won't really help you find any long-running checks because they won't report until they complete anyway. When it comes to measuring duration that feels more like a tracing concern.

@pivotal-jwinters Do you think that would be enough for measuring LIDAR health?

**Comment by cirocosta** [comment]
@vito I'll create an issue for that so we don't forget - for this PR, I'd say we can go ahead with the merge 👍

**Comment by pivotal-jwinters** [comment]
@vito @cirocosta yeah offloading some of the check metrics to tracing sounds like a good plan 👍

**Comment by cirocosta** [comment]
coool, created https://github.com/concourse/concourse/issues/5164 for it

**Pull request merged**
