### PR TITLE
atc: trace check & build creation

### LINKED ISSUE #5602: trace build creation
As a concourse operator
I want a way to link the [span context](https://github.com/concourse/concourse/pull/5575) associated with a resource version to the span context associated with a build
So that i can collect and reason about timing information for the complete causal flow of events through concourse

Given that a resource `r` has just checked
And produced a new version `v` with span context `sc`
And there is a job `j` with `r` as an input with `trigger: true`
When the scheduler creates a pending build `b` for `j`
Then `b`'s span context will be created with a [link](https://github.com/open-telemetry/opentelemetry-specification/blob/bdf39cb935a6f48badc687daeb78a66dc352761f/specification/overview.md#links-between-spans) to `sc`

**note** can we generalize the definition of `b` above to describe all cases where `b` is _caused by_ `v`? The definition of _cause_ has yet to be determined.

### PR DESCRIPTION
**Pull request by jamieklassen**
Branched from #5666, please review it first.

# Why is this PR needed?

Adding tracing to these components will enable end-to-end observability of the lidar & scheduler
components, which will be helpful for debugging and large-scale timing/performance measurements.

# What is this PR trying to accomplish?

closes #5602.

# How does it accomplish that?

* adds `span_context` column to `resource_config_versions` table
* propagate the span context for a check into new versions (leaving old versions alone)
* adds `span_context` column to `builds` table
* link the span context for a build to the span contexts for each of the versions that _caused_ that build

# Contributor Checklist

- [x] Unit tests
- [x] ~Integration tests~
- [x] Updated documentation (located at https://github.com/concourse/docs) - concourse/docs#335
- [x] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)

# Reviewer Checklist

- [x] Code reviewed
- [x] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [x] ~New config flags added? Ensure that they are added to the [BOSH](https://github.com/concourse/concourse-bosh-release) and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not displayed in the `--help` text).~

### CODE REVIEW

**Comment by zoetian** [comment]
When running the `create-and-run-new-pipeline` SLI, we get a trace like this in Jaeger:

Screen Shot 2020-05-27 at 4 39 48 PM

The long gap in the middle really demonstrates the effect of #5612!

**Comment by xtremerui** [comment]
> When running the `create-and-run-new-pipeline` SLI, we get a trace like this in Jaeger:
> 
> Screen Shot 2020-05-27 at 4 39 48 PM
> 
> The long gap in the middle really demonstrates the effect of #5612!

Is this something I should be looking for when doing acceptance test? What is the diff should I expecting on the jaeger UI between master and this pr? Thx!

**Comment by jamieklassen** [comment]
@xtremerui hmm I'll probably open a docs PR explaining the various operations that are being traced in this PR per concourse/docs#334. That should give a better sense of how to manually verify that this works.

**Comment by jamieklassen** [comment]
@xtremerui check out concourse/docs#335 for what you can expect to see. The parts where i mention one operation "following from" another operation is where you end up seeing spans in the same trace. I can't think of an obvious way to verify this beyond running the code on master and seeing a much more limited set of operations/generally smaller traces. This PR adds

* `scheduler.Run`
* `schedule-job`
* `job.EnsurePendingBuildExists`

as well as creating the links:
* `checker.Run` => `job.EnsurePendingBuildExists`
* `job.EnsurePendingBuildExists` => `build`

**Comment by jamieklassen** [comment]
@xtremerui rebased

**Pull request merged**
