### PR TITLE
Add new default values Guardian network-pool and max-containers

### PR DESCRIPTION
**Pull request by muntac**
## What does this PR accomplish?

Feature

Part of https://github.com/concourse/concourse/issues/5985

## Changes proposed by this PR:

If `--network-pool` is unset Guardian defaults to `10.80.0.0/22` which allows 1024 addresses, implicitly limiting a
Guardian worker to 250 containers (4 addresses reserved per container). This is true even if max-containers is set to
a higher value.

We set network-pool to `10.80.0.0/16` to increase the allowable addresses significantly ensuring the container
count is only limited by the explicit max-containers flag. If a user passes a custom value we use that instead.

**Update**
* Exposing both flags as options in the worker command now.
* Defaulting the maximum container limit to 250 to avoid stamping herd problem.
* Defaulting containerd max-container value to do the same.

More details on reasoning in an issue [comment](https://github.com/concourse/concourse/issues/5985#issuecomment-692202317).

## Notes to reviewer:
Inspecting processes running on a Guardian worker without having set `CONCOURSE_GARDEN_NETWORK_POOL` shows the following.
Screen Shot 2020-09-01 at 5 01 18 PM

When passing a custom value of `10.80.0.0/20`:
Screen Shot 2020-09-01 at 5 05 17 PM

**Related PRs**
https://github.com/concourse/concourse-chart/pull/150
https://github.com/concourse/concourse-bosh-release/pull/121

## Contributor Checklist

- [x] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [x] [Signed] all commits
- [ ] Added tests (Unit and/or Integration)
- [ ] Updated [Documentation]
- [ ] Added release note (Optional)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

### CODE REVIEW

**Comment by xtreme-sameer-vohra** [comment]
Would it make sense to pull this in into [GuardianRuntime](https://github.com/concourse/concourse/blob/master/worker/workercmd/worker_linux.go#L30) so its more explicit ?

**Comment by muntac** [comment]
@xtreme-sameer-vohra  @chenbh I believe Guardian specific flags were removed from the CLI listing i.e. [Guardian Runtime](https://github.com/concourse/concourse/blob/master/worker/workercmd/worker_linux.go#L30) for easier reasoning about the runtimes. The flags present under `GuardianRuntime` currently are Concourse specific, and all Guardian specific ones have to be looked up in the Guardian documentation. So I would prefer to note the default values in the docs site. Let me know your thoughts.

I posted a question in the BOSH release [PR](https://github.com/concourse/concourse-bosh-release/pull/121#issuecomment-689055455) about determining the default value of `max-containers` that we would like to put here.

> @xtreme-sameer-vohra I was unsure of what we should consider an average case upper limit with workload and machine variability taken into consideration.
> 
> I had thought we could have it unset initially and wait for feedback from users to see around what limits they start seeing problems. I haven't been able to find any past issues describing 250 being selected as the limit due to user feedback about performance. Mostly see stuff around the insufficient subnet problem, or hitting the max container limit.
> 
> Have you seen users run into performance problems where the issue was solved by limiting the number of containers?

**Comment by muntac** [comment]
I put in 250 for now, and noted in https://github.com/concourse/concourse/issues/6043 to test for new limits when we're doing drills for containerd vs guardian.

**Comment by xtreme-sameer-vohra** [comment]
> @xtreme-sameer-vohra @chenbh I believe Guardian specific flags were removed from the CLI listing i.e. [Guardian Runtime](https://github.com/concourse/concourse/blob/master/worker/workercmd/worker_linux.go#L30) for easier reasoning about the runtimes. The flags present under `GuardianRuntime` currently are Concourse specific, and all Guardian specific ones have to be looked up in the Guardian documentation. So I would prefer to note the default values in the docs site. Let me know your thoughts.
> 
> I posted a question in the BOSH release [PR](https://github.com/concourse/concourse-bosh-release/pull/121#issuecomment-689055455) about determining the default value of `max-containers` that we would like to put here.
> 
> > @xtreme-sameer-vohra I was unsure of what we should consider an average case upper limit with workload and machine variability taken into consideration.
> > I had thought we could have it unset initially and wait for feedback from users to see around what limits they start seeing problems. I haven't been able to find any past issues describing 250 being selected as the limit due to user feedback about performance. Mostly see stuff around the insufficient subnet problem, or hitting the max container limit.
> > Have you seen users run into performance problems where the issue was solved by limiting the number of containers?

It would be useful to document the default values in the binary `concourse worker -h` and the docs site, just so a user isn't surprised. I can see it becomes simpler to reason about Concourse specific flags (in Garden Runtime) and generic Garden flags(in Garden docs) with your distinction :)

**Review by xtreme-sameer-vohra — CHANGES_REQUESTED** [review]
Hey,
Looks like the wiring logic got dropped in the refactor. The two values aren't passed to gdn at the moment. They're just exposed in Concourse.

**Comment by muntac** [comment]
> Hey,
> Looks like the wiring logic got dropped in the refactor. The two values aren't passed to gdn at the moment. They're just exposed in Concourse.

Seeing the same :( Will let you know when I have a fix.

**Comment by muntac** [comment]
@xtreme-sameer-vohra fyi @taylorsilva and I pushed a fix but all the tests are breaking because of an elm package whose signature has changed at source.

**Comment by taylorsilva** [comment]
The elm stuff fixed itself. I'm rerunning all test suites.

**Review by xtreme-sameer-vohra — APPROVED** [review]
lgtm !!

**Pull request merged**
