### PR TITLE
web: pin menu polish

### LINKED ISSUE #3960: Pipeline view: Resource Pinning Polish
Users have been using this feature for sometime and based on user feedback we can add higher fidelity of polish to the pinning feature. 

## Inactive state of the pin icon

- [x] update to 'inactive' state, similar to the other icons in the app, of 0.5% opacity for consistency of UI app wide

UI_polish_pipeline_view_not_active

Screen Shot 2019-06-21 at 2 08 28 PM

## Active pinned resource dropdown list UI style Pipeline 

- [x] Bold the resource name and leave the version number unbolded
- [x] Active selection of the pin to display as full background colour change to #2A2929
- [x] Update list display UI to be consistent with sidebar 

Screen Shot 2019-06-21 at 2 18 56 PM

**Hover state on the list item**
Screen Shot 2019-06-21 at 2 30 09 PM

### PR DESCRIPTION
**Pull request by pivotal-jamie-klassen**
# Existing Issue

Fixes #3960.

# Changes proposed in this pull request

* increase size of pin icon
* light border on pin icon
* opacity change on pin icon hover
* click pin icon to toggle dropdown
* pin icon background and opacity reflect toggle state
* darker background, lighter text for dropdown items
* dropdown item background darkens on hover

# Contributor Checklist
- [x] Unit tests
- [x] ~Integration tests (if applicable)~
- [x] ~Updated documentation (located at https://github.com/concourse/docs)~
- [x] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)

# Reviewer Checklist
- [ ] Code reviewed
- [ ] Tests reviewed
- [x] ~Documentation reviewed~
- [ ] Release notes reviewed
- [ ] PR acceptance performed

### CODE REVIEW

**Comment by ddadlani** [comment]
I do not feel qualified to review the code, but I did acceptance. All the bullet points outlined under `Changes proposed` seem to work fine for Chrome as well as Safari.

There are just a couple things I want to confirm:
1) The pin button is greyed out when nothing is pinned, and does not change state even on hover.
2) Likely unrelated, but I cannot see the pin icon in the resource box in Safari (the pin icon in the top bar works fine). I have attached a picture to explain, but I don't think this PR should wait on it.

Screen Shot 2019-10-31 at 2 50 35 PM

**Comment by jomsie** [comment]
[I've created an issue for the lack of pin icon on safari. ](https://github.com/concourse/concourse/issues/4694)

**Comment by jomsie** [comment]
@ddadlani can I get another review? had to fix a conflict with release notes :)

**Comment by ddadlani** [comment]
can confirm, still works! still can't speak to the code :(

**Pull request merged**
