### PR TITLE
Fix formatting of example manifest

### PR DESCRIPTION
**Pull request by kkallday**
Move vm_extension description above the key to follow format of other manifest key descriptions.

### CODE REVIEW

**Comment by vito** [comment]
Seems fine as-is to me. The comment is attached to a single extension to replace, not the whole set of them.

**Comment by kkallday** [comment]
Hey @vito. In the integration tests for bbl (bosh-bootloader: https://github.com/pivotal-cf-experimental/bosh-bootloader/), we are deploying a bosh director and using it to deploy concourse. We are using a manifest packaged with our tests however we would like to pull the manifest from the concourse repo and replace values. This change would make it easier for us to do string replacement along with cleaning up the format of the comment.

**Comment by vito** [comment]
That feels like a weird coupling to me. Structurally updating the YAML rather than textually would be much more reliable. You'd be dealing with breakage all the time as we tweak comments/whitespace/etc.

**Comment by kkallday** [comment]
Yeah, thats a good idea. Thanks @vito!

**Pull request closed without merging**
