### PR TITLE
add pipeline examples to Tutorials page

### PR DESCRIPTION
**Pull request by afeld**

### CODE REVIEW

**Comment by afeld** [comment]
Looks like this page has now turned into [Tutorials](http://concourse.ci/tutorials.html), which the rest of these aren't. I still think it would be useful to list open source pipelines for reference...ideas about where that should live?

**Comment by vito** [comment]
Not sure yet. I've thought about having a 'pipeline gallery' of sorts, which could also be useful for sharing reusable pipeline templates.

**Comment by robdimsdale** [comment]
Not to take this conversation too far down a different track, but a pipeline gallery starts to answer the question of reusability and composability. Resources are deliverable, but there's no equivalent for task/job/pipeline config.

**Comment by robdimsdale** [comment]
Not to take this conversation too far down a different track, but a pipeline gallery starts to answer the question of reusability and composability. Resources are deliverable, but there's no equivalent for task/job/pipeline config.

**Comment by afeld** [comment]
Sooo, a standalone page then? Or combined with Tutorials?

**Comment by vito** [comment]
Let's start with a listing directly on the tutorial page for now. Something like:

```
(current content)

You may also want to just dive right in to some living, breathing Concourse pipelines. These aren't accompanied by documentation explaining them, but it may be useful just to see some real-world use cases:

* (concourse pipeline)
* etc
```

**Comment by afeld** [comment]
Updated!

**Comment by vito** [comment]
Looks good, thanks for putting this together!

**Pull request merged**
