### PR TITLE
Add pipeline config for redeploying concourse.

### PR DESCRIPTION
**Pull request by robdimsdale**
[#94528472]

### CODE REVIEW

**Comment by vito** [comment]
Awesome thanks! A few notes:

* Does the second `put` actually work? I thought we didn't respect `on: [failure]` if the previous step errored (which is how `put`s fail).
* Can we make the params be in the format of `foo-bar` for consistency with the other pipelines?
* Can probably remove the pipeline group since there's only one job in the whole thing.
* We should probably make the stemcell more generic so people can use this on vsphere to. So I think we can just rename `aws-stemcell` to `stemcell` and make the stemcell name parameterizable.

**Comment by robdimsdale** [comment]
Makes sense. I made the changes above.

i also opened #52 to enable retrying from tasks that have exited with error.

**Comment by vito** [comment]
perfect, thanks!

**Comment by drnic** [comment]
Thanks Rob!

**Pull request merged**
