### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by tomwhoiscontrary**
I thought you guys could do with a sweet logo so i made one.

### CODE REVIEW

**Comment by vito** [comment]
could you add more mustaches?

**Comment by tomwhoiscontrary** [comment]
You can have another moustache when you release 1.0.

**Comment by tomwhoiscontrary** [comment]
Okay how about this one.

concourse-ci

**Comment by vito** [comment]
c'mon tom

**Comment by vito** [comment]
stop it

**Comment by topherbullock** [comment]
I quite like it, actually.

**Pull request closed without merging**
