### PR TITLE
[6.7.x] Bump dex to 2.27.0

### PR DESCRIPTION
**Pull request by taylorsilva**
## What does this PR accomplish?
Bug Fix | Feature | Documentation

closes # .

## Changes proposed by this PR:
Same as #6370

## Release Note
* Bump Dex to 2.27.0 which fixes a vulnerability in the go XML library
* This is only a breaking change for the OIDC connector when the downstream provider returns a `preferred_username` claim
  * Previously, the `preferred_username` claim would be ignored in favor of the `--oidc-user-name-key` concourse auth flag.
  * Now, the `preferred_username` claim takes precedence so its value will be used as concourse OIDC username.

## Contributor Checklist

- [x] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [x] [Signed] all commits
- [ ] ~Added tests (Unit and/or Integration)~
- [ ] ~Updated [Documentation]~
- [x] Added release note (Optional)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

### CODE REVIEW

**Comment by xtremerui** [comment]
do we care about the errors for the release pipeline?

**Comment by taylorsilva** [comment]
@xtremerui I think the check don't work for the release branches :(

sadly I think there's more that needs to be done here. Got these errors locally when trying to compile the image:
```
# github.com/concourse/concourse/skymarshal/skycmd
skymarshal/skycmd/oauth_flags.go:85:3: unknown field 'GroupsKey' in struct literal of type oauth.Config
skymarshal/skycmd/oauth_flags.go:87:3: unknown field 'UserNameKey' in struct literal of type oauth.Config
skymarshal/skycmd/oidc_flags.go:73:3: unknown field 'GroupsKey' in struct literal of type oidc.Config
# github.com/concourse/concourse/skymarshal/storage
skymarshal/storage/storage.go:25:3: cannot use promoted field NetworkDB.Database in struct literal of type "github.com/concourse/dex/storage/sql".Postgres
skymarshal/storage/storage.go:26:3: cannot use promoted field NetworkDB.User in struct literal of type "github.com/concourse/dex/storage/sql".Postgres
skymarshal/storage/storage.go:27:3: cannot use promoted field NetworkDB.Password in struct literal of type "github.com/concourse/dex/storage/sql".Postgres
skymarshal/storage/storage.go:28:3: cannot use promoted field NetworkDB.Host in struct literal of type "github.com/concourse/dex/storage/sql".Postgres
skymarshal/storage/storage.go:29:3: cannot use promoted field NetworkDB.Port in struct literal of type "github.com/concourse/dex/storage/sql".Postgres
skymarshal/storage/storage.go:30:8: undefined: "github.com/concourse/dex/storage/sql".PostgresSSL
skymarshal/storage/storage.go:36:3: cannot use promoted field NetworkDB.ConnectionTimeout in struct literal of type "github.com/concourse/dex/storage/sql".Postgres
```

Looks like we should also back port #6195 first

**Comment by xtremerui** [comment]
right concourse needs to be updated to accommendate the dex changes from upstream.

**Comment by taylorsilva** [comment]
@xtremerui I back-ported the changes yesterday. I ran some testflight tests locally to verify the fix.

Looks like all the checks passed except for watjs (I remember now, the upgrade and downgrade checks don't work for the release branches). Re-running watjs as it looks like a flake.

**Comment by xtremerui** [comment]
updated the release note for the breaking changes of OIDC connector.

**Comment by xtremerui** [comment]
@taylorsilva it shows some conflicts after merging of the underscore PR. Could you fix the conflicts? THx a lot.

**Review by xtremerui — APPROVED** [review]

**Pull request merged**
