### PR TITLE
doc - azure documentation

### PR DESCRIPTION
**Pull request by sedouard**
Azure documentation for deploying concourse ci onto Azure!

### CODE REVIEW

**Comment by sedouard** [comment]
Hey @vito! Anything else you would need from me here?

**Comment by sedouard** [comment]
hey @vito I reduced the doc to exclude bosh azure specific instructions and point to bosh.io. I kept the deployment manifest for azure-vnet and kept the notes about where to get the azure stemcell. Anything else?

**Comment by sedouard** [comment]
hey @vito  is there anything else you need from me?

**Comment by vito** [comment]
Sorry to string you along - chatted with the BOSH PM and they'd rather wait until there are Azure stemcells/releases/docs on bosh.io before merging this, which sounds reasonable as most people have no reason to trust downloading a stemcell from "windows.net".

**Comment by sedouard** [comment]
Thanks for the update @vito. It seems like the [azure documentation](http://bosh.io/docs/azure-cpi.html) is live online and is marked as beta. It doesn't mention stemcell location because its using the [Azure Deployment Template](https://github.com/Azure/azure-quickstart-templates/tree/503618c60dafa067bef1bab667402ce1495e08b2/bosh-setup). 

You can see that the template refers to the [cloud foundry azure storage account](https://github.com/Azure/azure-quickstart-templates/blob/503618c60dafa067bef1bab667402ce1495e08b2/bosh-setup/bosh.yml#L26). Since there's already been a public media release, I would assume its reasonable for folks to trust this `cloudfoundry.blob.core.windows.net` stemcell link.

I guess my question is if the beta docs are on bosh.io and are being used today why block the docs here? Maybe just mark it as **beta** as the bosh.io docs do?

**Comment by sedouard** [comment]
*bump* any updates here?

**Comment by bingosummer** [comment]
@sedouard 
I add an ARM template to deploy concourse ci on azure.
https://github.com/Azure/azure-quickstart-templates/tree/master/concourse-ci

And for the manifest, I made a few changes.
https://github.com/Azure/azure-quickstart-templates/blob/master/concourse-ci/concourse.yml

Could you help take a look and see if the changes can be merged into your PR?
Thanks.

**Comment by sedouard** [comment]
@bingosummer :+1: awesome! i'll merge that into this branch today

**Comment by sedouard** [comment]
@bingosummer after the template is deployed, you still need to ssh into the devbox and upload the stemcell and releases, correct?

**Comment by sedouard** [comment]
@vito @bingosummer's [template folder](https://github.com/Azure/azure-quickstart-templates/tree/master/concourse-ci) includes the concourse ci manifest for azure-vnet (the same as you see in `manifests/azure-vnet.yml`. Does it make sense to keep that file here and link to it from the template, or does it make more sense to maintain it there? I'm thinking as changes happen to concourse, if you keep the infrastructure specific settings in one place you can update them all at once.

**Comment by bingosummer** [comment]
@sedouard 
Yes, need to upload the stemcell and releases.

**Comment by vito** [comment]
Hey, sorry for the radio silence.

We chatted about this in Slack a while back, and I was leaning towards closing it and actually ripping out *all* of our infrastructure-specific docs, in favor of looking forward to BOSH 2.0, which would allow us to have a single example manifest. We're still moving in that direction. Thanks for the effort in documenting this, but I'm going to close it and keep working on our new BOSH docs, which can hopefully defer to [bosh.io](https://bosh.io) entirely for the infrastructure-specific stuff. Sorry that this whole back-and-forth stretched on and led to just being closed.

**Pull request closed without merging**
