### PR TITLE
Conjur credential manager

### PR DESCRIPTION
**Pull request by AndrewCopeland**
# Why do we need this PR?
Conjur is a password vault that allows the ability to obtain secrets, this PR allows the ability to use the conjur password vault within concourse as a credential manager.

# Changes proposed in this pull request
> What are the changes included in this PR? Feel free to add as many lines as needed below.
* A new credential manager has been added.

# Contributor Checklist
> Are the following items included as part of this PR? Please delete checkbox items that don't apply.
- [ x] Unit tests
- [ ] Updated documentation (located at https://github.com/concourse/docs)
- [ x] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)

# Reviewer Checklist
- [x] Code reviewed
- [x] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed

### CODE REVIEW

**Comment by deniseyu** [comment]
hey @AndrewCopeland, thanks for rebasing! It looks like there are a few implementation problems from reading the tests:

```
atc/creds/conjur/conjur_factory.go:27:18: cannot use NewConjur(factory.log, factory.client, factory.secretTemplates) (type *Conjur) as type creds.Secrets in return argument:
	*Conjur does not implement creds.Secrets (wrong type for NewSecretLookupPaths method)
		have NewSecretLookupPaths(string, string) []creds.SecretLookupPath
		want NewSecretLookupPaths(string, string, bool) []creds.SecretLookupPath
atc/creds/conjur/manager_factory.go:15:9: cannot use &managerFactory literal (type *managerFactory) as type creds.ManagerFactory in return argument:
	*managerFactory does not implement creds.ManagerFactory (missing NewInstance method)
atc/creds/conjur/manager_factory.go:28:2: cannot use manager (type *Manager) as type creds.Manager in return argument:
	*Manager does not implement creds.Manager (missing Close method)
```

You can see the whole build log here: https://ci.concourse-ci.org/teams/main/pipelines/prs/jobs/testflight/builds/2461

I think these errors should be reproducible if you try to run `docker-compose up --build` with the configuration flags to enable Conjur passed in as environment vars to the web node. Let me know if you need any support with that!

**Comment by AndrewCopeland** [comment]
@deniseyu I am getting the same error on my side. I will try to debug. 
These testing passed before, and I have not made any changes to the the atc/creds/conjur folder since I submitted the PR.

**Comment by deniseyu** [comment]
thanks @AndrewCopeland and @cyberark-bizdev for the fixes! I have one more small request: It looks like maybe rebasing or merge conflict resolution went a little bit wonky and every commit is showing up three times. I have no problem with this change being multiple commits, but I suspect that the code won't compile at every commit currently in the history. Do you mind squashing down duplicate commits; alternatively, are you happy for us to squash everything down into one at merge time?

**Comment by AndrewCopeland** [comment]
On my side the concourse server is coming up and the my integration tests are passing. I want to look into the CI build failures however it appears I no longer have access to the concourse CI website.

Let me know if you need anything from me.

**Comment by evanchaoli** [comment]
> I want to look into the CI build failures however it appears I no longer have access to the concourse CI website.
> 

I see same problem. We are now no longer able to check build logs.

**Comment by AndrewCopeland** [comment]
@deniseyu You can squash all of them into one during merge time if that isn't a problem. Either way it looks like all of the tests are passing now. Please let me know if there is anything else you need from me to get this merged into master.

**Comment by AndrewCopeland** [comment]
Also when it comes to documentation will it automatically be generated from the `concourse web` cli or do I have to create a PR in https://github.com/concourse/docs.

**Comment by deniseyu** [comment]
@AndrewCopeland it's not autogenerated (I wish 😭) so you'll have to send a PR. The [Vault page](https://concourse-ci.org/vault-credential-manager.html) is a good one to copy the structure of.

**Pull request merged**
