### PR TITLE
Throw an error when the input version is not found

### PR DESCRIPTION
**Pull request by clarafu**
If we can't find a version for an input, we should throw an error while
we construct the plan.

Signed-off-by: Clara Fu <cfu@pivotal.io>

# Contributor Checklist
> Are the following items included as part of this PR? Please delete checkbox items that don't apply.
- [ ] Unit tests
- [ ] Integration tests (if applicable)
- [ ] Updated documentation (located at https://github.com/concourse/docs)
- [ ] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)

# Reviewer Checklist
> This section is intended for the core maintainers only, to track review progress. Please do not
> fill out this section.
- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the [BOSH](https://github.com/concourse/concourse-bosh-release) 
      and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not displayed in the `--help` text).

### CODE REVIEW

**Comment by clarafu** [comment]
@vito Could we just log the error without showing it in the UI?

**Comment by vito** [comment]
@clarafu no

**Comment by clarafu** [comment]
@vito image

**Comment by deniseyu** [comment]
Going to re-trigger testflight on this, it looks like a Docker flake

**Pull request merged**
