### PR TITLE
topgun/k8s: refactor tests to support targeting PKS

### PR DESCRIPTION
**Pull request by cirocosta**
Hey,

@taylorsilva and I started working on making the tests that currently fail on PKS (https://github.com/concourse/concourse/issues/4098#issuecomment-508549862) possible to run there.

Our approach is to conditionally `Skip()` based on the Kubernetes IAAS set (through environment variables). Trying to just fit another `if` in the current tests revealed that the code would become hard to reason about, so we started refactoring them:

- [x] `baggageclaim_drivers_test.go`
- [x] `container_limits_test.go`

Thanks!

### CODE REVIEW

**Comment by YoussB** [comment]
I was able to get a full run today with the current codebase, there seems to be some flakiness in some tests that must be related to: https://github.com/concourse/ci/issues/44

**Comment by YoussB** [comment]
makes sense, I can also add a fallback to GCP in case the variable is not set. So we can work on the other issue separately.

wdyt?

**Comment by taylorsilva** [comment]
Wondering if we should be testing on both GKE and PKS? My gut tells me we should otherwise we'll have some stale tests if we only run tests on one k8s engine. 

Kinda outside the scope of this story though. Figured we could talk about this in https://github.com/concourse/ci/issues/40

**Comment by YoussB** [comment]
@taylorsilva, I think we should be testing against both for sure, for the time being, until we figure out how we'll be testing on PKS I added the logic to default the testing to GKE if the environment variable is not set.

@cirocosta, it can safely be merged now, I guess.

**Pull request merged**
