### PR TITLE
7.4.x: add some DB optimizations

### PR DESCRIPTION
**Pull request by taylorsilva**
## Changes proposed by this PR

- [x] in-memory event ID's
- [x] only update resource config every minute
- [ ] ~don't update metadata if fetching from cache~
  - after reading over the code we determined this change isn't needed
- [x] close zstd in load_var_step to prevent memory leak

## Release Note

* DB optimizations
  * Increment an event ID in-memory instead of using a Postgres Sequence
  * Only update resource config if it hasn't been updated in a minute
  * Close zstd reader in load var step

### CODE REVIEW

**Comment by taylorsilva** [comment]
We tried running some tests locally and found out that this one commit also relies on a bunch of other changes that aren't in 7.4.x as well. There's a lot we need to backport or we need to make the commit from scratch based on the current state of 7.4.x

**Review by muntac — CHANGES_REQUESTED** [review]
Looks like the tests are failing on this [line](https://github.com/concourse/concourse/blob/35610af9f86663cd080399fadf7b5dc6a255fb3b/atc/db/build_factory_test.go#L443).

**Comment by taylorsilva** [comment]
Test is failing because the `eventID` was added to the build struct. When the build is fetched via the build_factory the eventID is not read from the DB and is zero. This clashes with the `build4DB` we kept in-memory which has an `eventID` of 1 because of the call to `build.Finish()`.

This made me realize that when we create a build that may already have events we start with eventID zero. I'm guessing this not what we want and that we would end up overwriting events or events may not appear in order.

**Review by muntac — APPROVED** [review]
LGTM!

**Pull request merged**
