### PR TITLE
ci: build rc image with 'file'

### PR DESCRIPTION
**Pull request by vito**
fixes https://github.com/concourse/concourse-docker/issues/38

### CODE REVIEW

**Comment by cirocosta** [comment]
Interesting, I wonder how this https://github.com/concourse/concourse/blob/e7f017be3ad546503412216f20134af2c09b5eaa/topgun/k8s/baggageclaim_drivers_test.go#L67-L76 passes then 🤔

**Comment by vito** [comment]
@cirocosta Hmm should we investigate that and confirm first then? I haven't manually verified this myself either.

**Comment by cirocosta** [comment]
Hmmm yeah, I was testing that like this:

```yaml
worker:
  nodeSelector:
    nodeImage: ubuntu

postgresql:
  persistence:
    enabled: false

concourse:
  web:
    kubernetes:
      keepNamespaces: false
  worker:
    baggageclaim:
      driver: btrfs
```

leading to the following failure:

```
{"timestamp":"2019-03-27T15:16:05.867273770Z","level":"error","source":"baggageclaim","message":"baggageclaim.fs.run-command.failed","data":{"args":["bash","-e","-x","-c","\n\t\tif [ ! -e $IMAGE_PATH ] || [ \"$(stat --printf=\"%s\" $IMAGE_PATH)\" != \"$SIZE_IN_BYTES\" ]; then\n\t\t\ttouch $IMAGE_PATH\n\t\t\ttruncate -s ${SIZE_IN_BYTES} $IMAGE_PATH\n\t\tfi\n\n\t\tlo=\"$(losetup -j $IMAGE_PATH | cut -d':' -f1)\"\n\t\tif [ -z \"$lo\" ]; then\n\t\t\tlo=\"$(losetup -f --show $IMAGE_PATH)\"\n\t\tfi\n\n\t\tif ! file $IMAGE_PATH | grep BTRFS; then\n\t\t\tmkfs.btrfs --nodiscard $IMAGE_PATH\n\t\tfi\n\n\t\tmkdir -p $MOUNT_PATH\n\n\t\tif ! mountpoint -q $MOUNT_PATH; then\n\t\t\tmount -t btrfs $lo $MOUNT_PATH\n\t\tfi\n\t"],"command":"/bin/bash","env":["PATH=/usr/local/concourse/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","MOUNT_PATH=/concourse-work-dir/volumes","IMAGE_PATH=/concourse-work-dir/volumes.img","SIZE_IN_BYTES=10266165248"],"error":"exit status 1","session":"3.1","stderr":"+ '[' '!' -e /concourse-work-dir/volumes.img ']'\n++ stat --printf=%s /concourse-work-dir/volumes.img\n+ '[' 10266165248 '!=' 10266165248 ']'\n++ cut -d: -f1\n++ losetup -j /concourse-work-dir/volumes.img\n+ lo=\n+ '[' -z '' ']'\n++ losetup -f --show /concourse-work-dir/volumes.img\nlosetup: /concourse-work-dir/volumes.img: failed to set up loop device: No such file or directory\n+ lo=\n","stdout":""}}
{"timestamp":"2019-03-27T15:16:05.867945721Z","level":"error","source":"baggageclaim","message":"baggageclaim.failed-to-set-up-driver","data":{"error":"failed to create btrfs filesystem: exit status 1"}}
```

I didn't rebuild the image with `file` though

**Comment by vito** [comment]
@cirocosta That `trigger-job` line needs `-w` to actually follow the build and ensure it passes. Maybe it's been false green this whole time?

**Comment by cirocosta** [comment]
hmmm makes sense.

And, indeed, with the following:

```Dockerfile
cat ./Dockerfile
FROM concourse/concourse:5.0.0

RUN apt update && apt install -y file
```

we're able to get the container up

**Pull request merged**
