### PR TITLE
web: striped animations and pause button colors

### LINKED ISSUE #2520: The "errored current" colour and "started" colour are very similar
# Feature Request

## What challenge are you facing?

When looking at builds, it can be unclear at times whether a job is `errored` or if it is `started`. Particularly if you are on an `errored` build:

screen shot 2018-08-22 at 11 09 16 am

This is particularly more noticeable on crappier monitors.

## A Modest Proposal

Make the `started` state have a different/more contrasty colour. Maybe have a way to indicate the build you've currently selected?

### LINKED ISSUE #3185: Trigger and abort button feedback
I'm not sure if I'm just used to the old design but I feel like the new trigger button color might make it look a little too separated from the job itself? 🤔 

screen shot 2019-01-31 at 12 14 47 pm

I think I might feel this way because the color of the button is the same as the grey page background and it makes the button seem disconnected or less important.

Another thing I noticed was when I trigger a new build, the abort button appears to the left of the trigger button. 

screen shot 2019-01-31 at 12 32 36 pm

job

I was wondering if we can make it a bit more scary or more obvious that it is a completely different button from the trigger one because at a quick glance it might seem quite similar but the abort button results in a destructive action.

cc @Lindsayauchin @vito 

Thanks! 👍

### PR DESCRIPTION
**Pull request by pivotal-jamie-klassen**
fixes #2520 
fixes #3185

Closes the old animation pr because this is on top of that

### CODE REVIEW

**Comment by xtreme-james-cooper** [comment]
Sorry about that, @pivotal-jamie-klassen XD

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin tagging you in regrading the type/location of the stripes and impact of color contrast on readability. I'd be fine with a yellow/black striped line along the top or something similar, which, as stated, circumvents all the troubles around synchronized stripes and color contrast pretty neatly. I might still vote in favour of having the whole banner colorful rather than black/grey by default.

**Comment by Lindsayauchin** [comment]
@pivotal-jamie-klassen @vito 

Updated design of the running animation to the style used on the dashboard pipeline card. 

Screen Shot 2019-03-11 at 11 16 53 AM
 

User feedback on the button with the status as the background colour was that it didn't look clickable. 
If we make the background on the button the same as the status can we add in a border to the button to indicate to the user this is a button and teh secondary darker colour background as the hover state? 

See examples: 

Screen Shot 2019-03-11 at 11 25 52 AM

Screen Shot 2019-03-11 at 11 23 10 AM

**Comment by vito** [comment]
@Lindsayauchin :+1: I find that button style clearer.

Now that the sawtooth pattern is up there it kind of encroaches on the header spacing, though I'm not sure how to avoid that since there's no space for the border otherwise. The dashboard doesn't have this problem because it always has a border up top, rather than filling in the header background. :thinking: 

The spacing is really only noticeable with the timestamps since they come closest to the edge. This is scope creeping a bit, but the timestamps were crammed up there back in 2014 without much thought and haven't moved since, so maybe it's time to finally move'em. :slightly_smiling_face:

**Comment by Lindsayauchin** [comment]
@pivotal-jamie-klassen I think we will have to either increase the overall height of that container by 8px

Screen Shot 2019-03-11 at 12 13 07 PM

Or we could change the layout of the time stamps like so..

Screen Shot 2019-03-11 at 2 07 59 PM

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin +1 for horizontal layout of timestamps

**Comment by pivotal-jamie-klassen** [comment]
my guess at the right behaviour for the status bar:
```
<div id="build-header" class="build-header" style="
  display: flex;
  justify-content: space-between;
  background: rgb(17, 197, 96);">
  <div style="display: flex;">
    <div style="
      border-width: 0 1px 0 0;
      border-color: #3d3c3c;
      border-style: solid;
      padding: 10px;
      font-size: 24px;
      font-weight: 300;
      display: flex;
      align-items: center;
      margin-left: 8px;">
      <a href="/teams/main/pipelines/states/jobs/resource-metadata">
        <span class="build-name">resource-metadata</span> #1
      </a>
    </div>
    <div style="
      border-width: 0 1px 0 0;
      border-color: #3d3c3c;
      border-style: solid;
      display: flex;
      flex-direction: column;
      justify-content: space-around;
      padding: 10px;
      width: 100px;">
      <div style="text-transform: uppercase; font-size: 10px;">started</div>
      <div style="font-size: 18px;">6m 28s ago</div>
    </div>
    <div style="
      border-width: 0 1px 0 0;
      border-color: #3d3c3c;
      border-style: solid;
      display: flex;
      flex-direction: column;
      justify-content: space-around;
      padding: 10px;
      width: 100px;">
      <div style="text-transform: uppercase; font-size: 10px;">finished</div>
      <div style="font-size: 18px;">6m 28s ago</div>
    </div>
    <div style="
      border-width: 0 1px 0 0;
      border-color: #3d3c3c;
      border-style: solid;
      display: flex;
      flex-direction: column;
      justify-content: space-around;
      padding: 10px;
      width: 100px;">
      <div style="text-transform: uppercase; font-size: 10px;">duration</div>
      <div style="font-size: 18px;">1h 2m</div>
    </div>
  </div>
  <div style="display: flex;">
    <button role="button" tabindex="0" aria-label="Trigger Build" title="Trigger Build" style="
      cursor: pointer;
      position: relative;
      background-color: rgb(17, 197, 96);
      padding: 10px;
      outline: none;
      margin: 0px;
      border-width: 0px 0px 0px 1px;
      border-color: rgb(61, 60, 60);
      border-style: solid;">
      <div style="
        width: 40px;
        height: 40px;
        background-position: 50% 50%;
        background-image: url("/public/images/ic-add-circle-outline-white.svg");
        background-repeat: no-repeat;">
      </div>
    </button>
  </div>
</div>
```
which looks like
Screen Shot 2019-03-12 at 2 48 19 PM

salient points are:
* each child of the left-aligned container have
    * 1px grey border on the right
    * 10px padding
* first child of the left-aligned container also has
    * extra 8px margin-left
    * font-size 24px, font-weight 300
    * vertically centers contents (`display:flex` + `align-items:center` in this case)
* every child of the left-aligned container after the first (they might well be called 'timestamp sections') has the same layout:
    * __fixed width of 100px__
    * aligns contents vertically, equalizing space on either side of each child
    * first child is all caps, font size 10px
    * second child has font size 18px

I'm dubious about the 100px fixed width in the interest of preserving the changes from #3333
It looks a bit like we should be willing to vary the width and/or the font size of the timestamp itself depending on whether it is relative or verbose. For example, a verbose timestamp at 18px, if required to stay on one line, can force the width all the way to 225px:
Screen Shot 2019-03-12 at 3 05 15 PM

Here we find ourselves quickly running out of horizontal real estate, even with a moderate-length job name and only one of the timestamps being verbose.

Another idea, if we're willing to compromise on some alignment and font size (10px is probably getting into truly inaccessible territory):
Screen Shot 2019-03-12 at 3 17 03 PM


@Lindsayauchin I liked the idea at first, but now we have a real yak to shave.

**Comment by pivotal-jamie-klassen** [comment]
another draft after pairing with @Lindsayauchin 
```
<div id="build-header" class="build-header" style="
  display: flex;
  justify-content: space-between;
  background: rgb(17, 197, 96);">
  <div style="display: flex;">
    <div style="
      border-width: 0 1px 0 0;
      border-color: #419867;
      border-style: solid;
      padding: 10px;
      font-size: 24px;
      font-weight: 300;
      display: flex;
      align-items: center;
      margin-left: 8px;
      ">
      <a href="/teams/main/pipelines/states/jobs/resource-metadata">
        <span class="build-name">resource-metadata-resource-metadata-resource-metadata</span> #1
      </a>
    </div>
    <div style="
      border-width: 0 1px 0 0;
      border-color: #419867;
      border-style: solid;
      display: flex;
      flex-direction: column;
      justify-content: space-around;
      padding: 5px 10px;
      width: 100px;
      ">
      <div style="text-transform: uppercase;font-size: 12px;">started</div>
      <div style="font-size: 12px;line-height: 1;">Feb 13 2019</div><div style="
    font-size: 16px;
"> 04:35:51 PM</div>
    </div>
    <div style="
      border-width: 0 1px 0 0;
      border-color: #419867;
      border-style: solid;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      padding: 5px 10px;
      width: 100px;
      ">
      <div style="text-transform: uppercase;font-size: 12px;">finished</div>
      <div style="font-size: 16px;">6m 28s ago</div>
    </div>
    <div style="
      border-width: 0 1px 0 0;
      border-color: #419867;
      border-style: solid;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      padding: 5px 10px;
      width: 100px;
      ">
      <div style="text-transform: uppercase;font-size: 12px;">duration</div>
      <div style="font-size: 16px;">1h 2m</div>
    </div>
  </div>
  <div style="display: flex;">
    <button role="button" tabindex="0" aria-label="Trigger Build" title="Trigger Build" style="
      cursor: pointer;
      position: relative;
      background-color: rgb(17, 197, 96);
      padding: 10px;
      outline: none;
      margin: 0px;
      border-width: 0px 0px 0px 1px;
      border-color: rgb(61, 60, 60);
      border-style: solid;">
      <div style="
        width: 40px;
        height: 40px;
        background-position: 50% 50%;
        background-image: url(" public="" images="" ic-add-circle-outline-white.svg");="" background-repeat:="" no-repeat;"="">
      </div>
    </button>
  </div>
</div>
```

**Pull request merged**
