### PR TITLE
stepTree: Disable autoexpand until #3521 is fixed.

### PR DESCRIPTION
**Pull request by kallisti5**

### CODE REVIEW

**Comment by kallisti5** [comment]
Feel free to revert once #3521 is fixed

**Comment by kallisti5** [comment]
Builds for me.
```
$ /home/kallisti5/Code/concourse/node_modules/elm/bin/elm make src/Build/StepTree/StepTree.elm
Success!                                                             
```

**Comment by vito** [comment]
Does this result in a measurable performance improvement? :thinking: I thought most of the time spent was in processing the events, not rendering the output. The events are processed regardless of whether the step is expanded or collapsed.

**Comment by kallisti5** [comment]
Part of it is just the browser showing huge of text from long builds.

Example data:
  https://build.haiku-os.org/buildbot/#/builders/1/builds/10/steps/16/logs/stdio

When concourse shows the build status, it seems to render all 17,000+ lines over and over which kills the browser performance. It's difficult to even scroll to the top of the page to "unexpand" the task.

After much clicking, if you're able to get to the top of the page, collapsing results in the page working as expected (except, a bit sluggish)

Also, this shouldn't be a client performance issue.  Running a Ryzen 1800x here with Chrome.. so that's a near best-case client.

**Comment by kallisti5** [comment]
I've pushed out my initial work here:
  https://github.com/haiku/infrastructure/tree/master/playground/concourse

It assumes you're using the stock docker-compose deployment of concourse.

Once you're logged in via fly:
```
./apply-lifecycle.sh master secrets.source
```

Fire off a build of haiku / master-x86_64, and enjoy your browser crawling in a panic to keep up :-)

**Comment by vito** [comment]
> When concourse shows the build status, it seems to render all 17,000+ lines over and over which kills the browser performance. It's difficult to even scroll to the top of the page to "unexpand" the task.

That sounds strange. Could be a performance regression. We do all kinds of lazy-rendering to prevent it from having to re-draw everything. I think that warrants investigation before collapsing steps by default. :thinking: Especially if the page remains sluggish after collapsing the step.

/cc @pivotal-jamie-klassen

**Comment by pivotal-jamie-klassen** [comment]
We have validated that this is a decent stopgap with the following experiment:

We replaced [the openEventStream callback](https://github.com/concourse/concourse/blob/master/web/public/index.html#L202-L226) with
```javascript
app.ports.openEventStream.subscribe(function(config) {
  var openEvent, statusEvent, initializeEvent, finishTaskEvent, finalStatusEvent, endEvent
  // ... defining these dummy events
  var logEvent = {
    type: "event",
    target: {url: "http://localhost:8080/api/v1/builds/1/events"},
    data: `{
      "data":{
        "time":1560959925,
        "origin":{"id":"5d0a5ba8","source":"stderr"},
        "payload":"some long line of log output\\n"
      },
      "event":"log",
      "version":"5.1"
    }`
  };
  var buffer = [openEvent, statusEvent, initializeEvent]
    .concat(Array(10000).fill(logEvent))
    .concat([finishTaskEvent, finalStatusEvent, endEvent]);
  function flush() {
    if (buffer.length > 0) {
      app.ports.eventSource.send(buffer);
      buffer = [];
    }
  }
  setInterval(flush, 200);
});
```
which means that loading `http://localhost:8080/builds/1` will always mean a single Elm update loop occurs with a batch of 10000 identical events. We profiled build page with auto-expanding steps and saw this:

Screen Shot 2019-06-19 at 2 52 26 PM

We see ~2.7 seconds spent on
1. our Elm code processing the events
2. the Elm runtime updating the virtual DOM
3. the browser recomputing styles/repainting

Then we applied the change in this PR and saw this:
Screen Shot 2019-06-19 at 2 53 12 PM
We see ~1 second spent almost entirely on processing the batch of events with minimal effort on the Elm runtime or layout engine's part.

Furthermore, we have anecdotally observed that log lines don't actually take longer and longer to render as the output gets longer -- the real expense is just loading a huge amount of events on the first page load, so the above sample should be representative.

This gives a fair amount of confidence that there is no obvious inefficiency causing auto-expanded steps to be expensive; rather, we will need to think carefully about optimizing/offloading the three steps above. So @xtreme-james-thomson and I will open another PR that does the same as this one as well as some refactoring cleanup.

Upon discussion with @vito we agreed that this is a reasonable compromise to make in the interest of performance, and we could think of a couple other reasons why collapsing all steps on page load might be desirable.

**Comment by vito** [comment]
> Upon discussion with @vito we agreed that this is a reasonable compromise to make in the interest of performance, and we could think of a couple other reasons why collapsing all steps on page load might be desirable.

The other reason is mainly that auto-expanding can actually make it difficult to see which steps failed, since the output pushes the rest of the steps off-screen. For example, if you've got an `in_parallel:` with 3 tasks and task 2 and 3 fail, you'd probably only see task 2 on first page load and have no idea task 3 also failed as its step header gets pushed offscreen.

So with that + the performance justification I think we can go forward with this change not only as a stopgap solution but as a potential UX improvement. :slightly_smiling_face: 

Thanks for the idea, @kallisti5!

**Comment by kallisti5** [comment]
Glad this is getting fixed!

If you're looking to give a quick status overview, you could track the "number of log lines per build step". Jenkins and buildbot use these numbers to calculate a rough progress bar. (if the last run of this step was 1000 lines, then since this step has produced 200 lines it is likely ~20% done)

Anyway, that's a good enhancement for another ticket.   Thus unblocks haiku-os.org from potentially using concourse.ci for their (complex) builds.

Thanks!

**Comment by vito** [comment]
@kallisti5 Nice, didn't know Haiku were evaluating Concourse! That's a cool project, I remember [hacking aroud with it](https://github.com/vito/MusicPlayer) a long while back.

Also this is out in v5.4 now. I think auto-collapsing for finished builds makes sense, though as a follow-up we can make it a bit easier to notice where the failure is. I opened #4111 for that.

Also, do you think there's a middle ground where we still auto-expand for in-flight steps? Or was that the source of the slowness? In my experience running builds are less laggy than finished ones, and it's otherwise nice to be able to just click in to a build and watch all the output from beginning to end. As it's implemented right now I have to expand each step.

Thanks!

**Comment by kallisti5** [comment]
@vito you can look at our current deployment of concourse now for some ideas on how 5.4.0 reacts to large builds.  It's still slow, but somewhat better.

What's weird is when the build is running, you have to wait for each task to "repopulate"
(Each step spins as busy for 20+ seconds, then moves onto the next. It looks like the build is "still happening on those steps, but it is just "replaying the logs" behind the scenes)

This is the "longest" one:
https://ci.haiku-os.org/teams/nightly/pipelines/toolchain-master

**Comment by kallisti5** [comment]
Also to compare:
https://build.haiku-os.org/buildbot/#/builders/1/builds/16

For all of buildbot's faults, their status page loads *really* quickly and is precise due to loading only the last ~40 log lines until you dig into details. I still think that's the "real" long-term answer.

**Pull request closed without merging**
