### PR TITLE
web: dashboard job preview of paused job is blue

### LINKED ISSUE #2323: Paused jobs that would run if they weren't paused show up in dashboard as if they were running
# Bug Report

In the following pipeline, all the left-hand column jobs are paused except the bottom one. Despite this, there are two with the moving-diagonal-"I'm running" stripes.
 
screen shot 2018-06-26 at 5 24 55 pm
[From this pipeline](https://buildpacks.ci.cf-app.com/dashboard)

These jobs would like to run, but are waiting to be unpaused before starting. If they aren't going to look just like not-trying-to-run paused jobs, I'd expect blue diagonal stripes (to distinguish them from actually running jobs).

* Concourse version: v3.14.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? Probably not.

### PR DESCRIPTION
**Pull request by pivotal-jamie-klassen**
Fixes #2323

### CODE REVIEW

**Comment by xtreme-james-cooper** [comment]
This one sits on top of the other larger pr, right?

**Comment by vito** [comment]
@pivotal-jamie-klassen Does this need a rebase?

**Comment by pivotal-jamie-klassen** [comment]
... for a few rebases more

**Comment by vito** [comment]
WE DID IT

**Pull request merged**
