### PR TITLE
Add flag to enable or disable public pipelines

### PR DESCRIPTION
**Pull request by maxknee**
## What does this PR accomplish?

Bug Fix | Feature | Documentation

closes # .

## Changes proposed by this PR:

As our concourse instance grows, we've found that
by hiding public pipelines via a command flag,
we are able to increase the performance of our system.

This should be used when needed to hide pipelines when
a large amount of users don't need or want to see other
teams' exposed pipelines.

## Notes to reviewer:

By spinning up and setting up public pipelines, then logging out and seeing that they are not visible. 
## Contributor Checklist

- [X] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [X] [Signed] all commits
- [X] Added tests (Unit and/or Integration)
- [ ] Updated [Documentation]
- [X] Updated [Release notes]

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs
[Release notes]: https://github.com/concourse/concourse/tree/master/release-notes

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

### CODE REVIEW

**Comment by clarafu** [comment]
Hi @maxknee, thanks for your work on this PR! I wanted to discuss with you a bit more about the problems you are facing around dashboard performance and cluttering of dashboard views with public pipelines.

We currently have some tracks of work that tackle those similar problems. We have had many performance improvements with the work done in https://github.com/concourse/concourse/issues/5712, I was wondering what version of Concourse you are running where you are still seeing performance problems with the dashboard?

For your other problem of not needing to see public pipelines from other teams in order to reduce clutter, I think that is a very reasonable use case because I also agree with it. Most of the time in multi-tenant environments, you will never need to care about other team's pipelines. I'm wondering rather than having it be a flag set on the ATC, that can be tackled with some changes to the dashboard UI? I want to pull in @matthewpereira because I know he can probably provide a lot more insight into if there is an existing issue that addresses this problem already or if not, he might have some suggestions on what it might look like.

**Comment by maxknee** [comment]
Hey @clarafu, so we run a REALLY big instance of concourse, where we have 17000+ public jobs, and across 8 load balanced ATCs, we were having severe latency issues where our `listalljobs` endpoint would be 5+ seconds to load. we have 4952 pipelines and 1045 public pipelines. 
image (2)

It's not that the UI is cluttered per se, BUT the payload and then parsing of json for everyone using concourse became clear that there were a lot of issues with dashboard performance lending to a degraded user experience. 
I'd also like to point out that rate limiting would probably not help in this case because the experience would be non-existent for a large sum of our users. 

Let me know what you think and thanks for looking at my PR

**Comment by mdb** [comment]
To further color some of what @maxknee has shared (we are on the same team), it's perhaps also worth noting that, in addition to dramatically improving HTTP latency (and thus the time required to render a usable homepage), hiding public pipelines yielded other positive performance benefits throughout the system, including...

* reduced ATC CPU consumption
* notably increased database throughput (queries performed per second)
* reduced database load

Unfortunately, I don't have Grafana graphs illustrating all of this in great detail, though here's a graph illustrating the stabilization of database load following our May 20th deployment of @maxknee 's patch disabling the inclusion of public pipelines in `listAllJobs`:

image

**Comment by clarafu** [comment]
@maxknee Thanks for the detailed explanation of your use case! We also noticed that the ListAllJobs endpoint was causing a lot of problems so we did a lot of work to improve it within the v6.0 release. You can find all the changes here https://github.com/concourse/concourse/releases#60-dashboard but I think one that is worth noting is that the endpoint no longer needs to decode the job config which we found to be a big source of the problem with how much computational resources the endpoint takes up. We also made improvements on lazy loading the dashboard so that users will not be stuck waiting for all the jobs/pipelines to load up before displaying anything.

The reason why I'm trying to figure out if there are other ways to solve the problems you are facing is because it seems like your main problem is not that you want to only see public pipelines (which could be solved through some changes to the dashboard UI) but more that the dashboard is very costly and this PR is a way to reduce the amount of data it needs to load. I'm worried that if we merge this PR and the problem goes away, as your deployment continues to grow in the number of pipelines that each team has, it might get to a point where the dashboard needs to load up a large number of pipelines again and you will see the same problem with degrading dashboard performance as you do now. I am hoping that we can tackle the underlying problem of the high dashboard CPU consumption rather than a possibly temporary solution to the problem.

I'd like to ask you to try out the latest version of Concourse with the existing dashboard improvements and see if it helps fix the performance. If after upgrading you don't see enough improvements, we can discuss further how we can make the dashboard more performant! 😄

**Comment by maxknee** [comment]
@clarafu excellent, but what about database performance improvement? we have a very large RDS instance and coupled with lazily loading and other optimizations, would that also have a benefit?

we're working on trying to replicate what we have on a smaller scale to test 6.3 to see if this patch is needed or not. (but performance testing is hard)

**Comment by ndmmcglynn** [comment]
@clarafu thanks for your replies and we are happy to see new the performance improvements and will test them. Personally, I tend to agree with your point below and do think there is pretty substantial UX clutter when the number of public pipelines reaches the 1k+ scale. It is no longer helpful to users (especially new ones) to have so much unrelated information hitting them at once which is why having the ability to disable this would be advantageous. Curious to hear thoughts from @matthewpereira as well!

> For your other problem of not needing to see public pipelines from other teams in order to reduce clutter, I think that is a very reasonable use case because I also agree with it. Most of the time in multi-tenant environments, you will never need to care about other team's pipelines. I'm wondering rather than having it be a flag set on the ATC, that can be tackled with some changes to the dashboard UI? I want to pull in @matthewpereira because I know he can probably provide a lot more insight into if there is an existing issue that addresses this problem already or if not, he might have some suggestions on what it might look like.

**Comment by clarafu** [comment]
@maxknee There were some database CPU improvements with v6.0.0 because of the changes to the algorithm component. You can read about it here https://github.com/concourse/concourse/releases#3602, it also shows a before and after metric of the database CPU. 

@ndmmcglynn Right I definitely agree with the use case of being able to hide public pipelines because of the clutter it introduces in the dashboard especially for multi-tenant environments. I'm hoping if v6.x helps fix your ATC/DB CPU consumption, we can shift the focus of this conversation onto the details of that feature instead (if you would be interested)!

**Comment by matthewpereira** [comment]
Hey folks, thanks for your patience with this issue. I've been tied up in other work all week, and didn't notice the Github mention.

Now that we've made the 6.x.x improvements to the scheduling algorithm, the DOM performance in the web UI, and added a few patches to give more options for limiting the ListAllJobs endpoint, the next two big initiatives we have underway for decluttering and improving the front-end experience are:
* #5648 Archiving pipelines - this should help simplify what you're seeing on the dashboard unless you specifically want to look for an archived pipeline, making it faster to navigate to important pipelines as part of your everyday workflows
* #5434 Favorite pipelines - likewise, this should make it faster to navigate to important and frequently-visited pipelines

However, neither of these really do too much to decrease bandwidth usage or make the interface more *responsive*. To that end we have a new concept of a view selector in the works that could allow you to switch between viewing different *types* of pipelines - eg, show only the failed-state pipelines, only the paused-state pipelines, only the error-state pipelines, only the archived pipelines, only the favorite pipelines - and we could probably extend that, but I'm wondering what the hierarchy should be. 

I like the idea of being able to hide public pipelines from other teams as well, but I'll have to think of the best place for this sort of switch or toggle to live in the UI. Should this be another *type* of pipeline that we can filter by, or would you folks think it's more useful for example to be able to `Filter to show only [Failed|Errored|Archived|Paused] Pipelines` and then `Show/Hide other teams' public pipelines` as two separate levels of filtering?

**Comment by maxknee** [comment]
> Hey folks, thanks for your patience with this issue. I've been tied up in other work all week, and didn't notice the Github mention.
> 
> Now that we've made the 6.x.x improvements to the scheduling algorithm, the DOM performance in the web UI, and added a few patches to give more options for limiting the ListAllJobs endpoint, the next two big initiatives we have underway for decluttering and improving the front-end experience are:
> 
> * #5648 Archiving pipelines - this should help simplify what you're seeing on the dashboard unless you specifically want to look for an archived pipeline, making it faster to navigate to important pipelines as part of your everyday workflows
> * #5434 Favorite pipelines - likewise, this should make it faster to navigate to important and frequently-visited pipelines
> 
> However, neither of these really do too much to decrease bandwidth usage or make the interface more _responsive_. To that end we have a new concept of a view selector in the works that could allow you to switch between viewing different _types_ of pipelines - eg, show only the failed-state pipelines, only the paused-state pipelines, only the error-state pipelines, only the archived pipelines, only the favorite pipelines - and we could probably extend that, but I'm wondering what the hierarchy should be.
> 
> I like the idea of being able to hide public pipelines from other teams as well, but I'll have to think of the best place for this sort of switch or toggle to live in the UI. Should this be another _type_ of pipeline that we can filter by, or would you folks think it's more useful for example to be able to `Filter to show only [Failed|Errored|Archived|Paused] Pipelines` and then `Show/Hide other teams' public pipelines` as two separate levels of filtering?

^ I do like having extra filtering. If there's a way to ensure that we can set a default filtering as well, just to give our instance a some breathing room.

**Comment by Haegi** [comment]
Is there any progress on this one?

**Comment by xtremerui** [comment]
@clarafu could you provide an update please?

**Comment by clarafu** [comment]
I'm going to close this PR for now because I think it was trying to solve a performance problem that will probably be better solved in a different way (either through performance optimizations or through a filter in the dashboard web UI). Feel free to open the issue if you feel differently and want to continue to work on this PR!

**Comment by clarafu** [comment]
I'm going to close this PR for now because I think it was trying to solve a performance problem that will probably be better solved in a different way (either through performance optimizations or through a filter in the dashboard web UI). Feel free to open the issue if you feel differently and want to continue to work on this PR!

**Pull request closed without merging**
