### PR TITLE
[#4200] reduces overhead of TLS db connections

### PR DESCRIPTION
**Pull request by ebilling**
From my testing with at the level of 6k requests I'm seeing a drop in CPU of approximately 30% by re-using database connections rather than letting them get reaped when they go idle.  For TLS connections re-establishing the connection is very expensive.

### CODE REVIEW

**Comment by ebilling** [comment]
Sorry, picked up some changes I wasn't planning to take.  Will trim and resubmit.

**Comment by vito** [comment]
FWIW I think you can also just `git push -f` and the PR will auto-update.

**Comment by ebilling** [comment]
I took care of it.  Which branch would you prefer I do the pull request to?  Master or release/4.5.x?

**Comment by vito** [comment]
@ebilling Late reply, but always `master`. :)

**Pull request closed without merging**
