### PR TITLE
Added formatted email resource

### PR DESCRIPTION
**Pull request by santoshjpawar**
https://github.com/santoshjpawar/concourse-email-notification

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@santoshjpawar Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/concourse&pullRequestId=969)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/concourse&pullRequestId=969) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@santoshjpawar Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/concourse&pullRequestId=969)!

**Comment by santoshjpawar** [comment]
Thank you @vito. When will this be reflected in the online documentation?

**Comment by santoshjpawar** [comment]
@vito when will this be reflected in the online documentation?

**Pull request merged**
