### PR TITLE
Missing exiter.ps1 in worker_version-windows

### PR DESCRIPTION
**Pull request by RomRider**

### CODE REVIEW

**Comment by RomRider** [comment]
It fails to pre-compile on bosh:
```
Task 4 | 20:16:49 | Compiling packages: worker_version-windows/9ce9fe16b60a18cd12483215366f2f15f4498797 (00:00:37)
                   L Error: Action Failed get_task: Task 3404b69f-6955-436f-73fc-781f8874f965 result: Compiling package worker_version-windows: Running packaging script: Running packaging script: Command exited with 127; Stdout: , Stderr: packaging: line 1: ./exiter.ps1: No such file or directory
+ Copy-Item worker-version/version /version
packaging: line 5: Copy-Item: command not found
```

**Comment by ramonskie** [comment]
yes someone reverted my commit by adding the exiter.ps1 from the spec files

**Comment by ramonskie** [comment]
tested this pr works like a charm please merge :+1:

**Comment by vito** [comment]
thanks!

**Pull request merged**
