### PR TITLE
Use c4.large instances types for compilation.

### PR DESCRIPTION
**Pull request by robdimsdale**
- instead of c3.
- use 30GB of ephemeral disk.

### CODE REVIEW

**Comment by zachgersh** [comment]
@robdimsdale just a point of clarification - why is the ephemeral disk being included?

**Comment by robdimsdale** [comment]
@zachgersh c4.x instance types do not have any ephemeral disk - we have to bind our own if we need it (which we do)

**Comment by zachgersh** [comment]
LGTM then - @vito ok to merge?

**Comment by vito** [comment]
Yep

**Pull request merged**
