### PR TITLE
#3819 changing streamIn/Out to zstdEncoding

### PR DESCRIPTION
**Pull request by kcmannem**
after the merge of https://github.com/concourse/baggageclaim/pull/22 , we can switch over the streaming to zstd.

Signed-off-by: Divya Dadlani <ddadlani@pivotal.io>
Co-authored-by: Krishna Mannem <kmannem@pivotal.io>

### CODE REVIEW

**Comment by ddadlani** [comment]
After talking with @vito, we can bump the workers by a minor version to address the upgrade issue, so that the ATC will ignore older workers until they are upgraded. This would remove the need for supporting gzip for older workers.

**Comment by ddadlani** [comment]
Fixes #3819

**Comment by kcmannem** [comment]
@ddadlani approve plz

**Comment by kcmannem** [comment]
@cirocosta coming soon, drills tests are finished and we know the efficiency gains.

**Comment by vito** [comment]
@kcmannem Where can I see those efficiency gains? Could put some links or metrics screenshots here for posterity?

**Comment by kcmannem** [comment]
@vito done the changes. We need to wait for this pr to be merged into ci https://github.com/concourse/ci/pull/23 so that fly builds are updated. You can merge this in after that.

**Comment by pivotal-jamie-klassen** [comment]
concourse/ci#23 is merged!

**Comment by cirocosta** [comment]
@kcmannem did you end up checking if those spikes where also due to parallelism? 🤔  

If so, it'd perhaps be good to make that configurable, as the way that the number of threads decided to be used (I guess, number of available virtual cores) might not be very accurate when running `concourse worker`s within containers (where the number of available processes don't necessarily match the limits of set for the container 🤔 )

Wdyt?

thanks!

**Comment by kcmannem** [comment]
@vito are we waiting on something here? can we merge?

**Comment by vito** [comment]
Looks like a couple of conflicts need to be resolved. Otherwise good to go.

**Pull request merged**
