### PR TITLE
Warn on unused resources vs erroring out

### PR DESCRIPTION
**Pull request by xtremerui**
resubmitting of #4178

### CODE REVIEW

**Comment by cirocosta** [comment]
Hey @xtremerui,

@aoldershaw and I were taking a look at the changes, here are some things we
noticed:

1. without any changes to `fly`, the warning shows as a deprecation notice:


```console
$ fly -t local set-pipeline -p test -c ./pipeline.yml
resources:
  resource repository has been added:
+ name: repository
+ source:
+   uri: http://github.com/concourse/concourse
+ type: git

jobs:
  job test has been added:
+ name: test
+ plan:
+ - config:
+     container_limits: {}
+     image_resource:
+       source:
+         repository: busybox
+       type: registry-image
+     platform: linux
+     run:
+       path: "true"
+   task: test

apply configuration? [yN]: y

DEPRECATION WARNING:
  - resource 'repository' is not used in pipeline

pipeline created!
you can view your pipeline here: http://localhost:8080/teams/main/pipelines/test
```

It seems like some work could be done over here:
https://github.com/concourse/concourse/blob/8153ad08f7963b91fdf1f658820029341ea05edb/fly/commands/internal/displayhelpers/error_handling.go#L12-L43


2. having the check being implicitly performed inside `validateResourceTypes`
seems odd - perhaps it'd be better if not placed within `validateResourceTypes`
as it's not only about resource types?

https://github.com/concourse/concourse/pull/5060/files#diff-a86e8b6a0cbf3c90b8f1f94e47230d31R181


Wdyt?

thanks!

**Comment by cirocosta** [comment]
With regards to @clarafu 's point here https://github.com/concourse/concourse/issues/4177#issuecomment-516100938 - should we perhaps make very clear to the user that they are about to have unnecessary checks going on?

**Comment by xtremerui** [comment]
@cirocosta hmm thinking about it again I agee that unused resource should not check implicitly.

**Comment by clarafu** [comment]
I think this PR might be feasible after we implement https://github.com/concourse/concourse/issues/4944! Which is to only check resources that are used as an input to a job.

**Comment by xtremerui** [comment]
I will leave the original issue open and make it `blocked` until #4944 is done. Thx @clarafu !

**Comment by rajatrj16** [comment]
Do we have a solution for the unused vars? 
```
WARNING:
Error loading existing config:
  - invalid resources:
        resource 'docker-image-dummy' is not used
        resource 'docker-test-image-dummy' is not used

error: configuration invalid
```
I am using this in the put resource

**Pull request closed without merging**
