### PR TITLE
Appends resource type to the name on the resource details page

### LINKED ISSUE #3169: Resource types displayed on details page
screen shot 2019-01-29 at 3 46 08 pm

## What challenge are you facing?

It's hard to tell what resource type a resource is when looking at the resource details page.

## What would make this better?

It would be great to display a resource's current type in the web UI so all context is available. Right now, putting types in the resource name is the way you provide context to the metadata display on that page.

## Are you interested in implementing this yourself?

Heck yaw!

/cc @ddadlani

### PR DESCRIPTION
**Pull request by osis**
Resolves #3169

### CODE REVIEW

**Comment by osis** [comment]
Sorry, this is a WIP.

**Comment by osis** [comment]
This should be stable now.

cc/ @pivotal-jamie-klassen @xtreme-james-cooper to take a peek whenever they have slack.

**Comment by cirocosta** [comment]
That's pretty nice! 

I suppose not updating the `title` is desired. Is it?

screenshot from 2019-02-06 11-21-35

thx!

**Comment by osis** [comment]
Naw, I didn't want to add it to the title. I figured it should match the object you interacted with to get to that page vs the details displayed on the page itself, but it's a loosely held opinion. /cc @Lindsayauchin 

Haha yea I went simple in terms of styling and Concourse is very flexible in terms of inputs. I wonder want would happen if someone had a "this-name-is-way-too-long-for-the-ui-to-handle" resource 😄.

I guess that might be handled in https://github.com/concourse/concourse/issues/2781.

**Comment by Lindsayauchin** [comment]
@osis I worry about how long those titles will get! But, I like the freedom and the simplicity of the solution and it is resolving this pain for some users in a really simple way. Would this go away if we added an icon beside a resource or remain? https://github.com/concourse/concourse/issues/3169

**Comment by osis** [comment]
@Lindsayauchin I'm not sure how you can introduce icons because there the amount of resource types can be infinite.

**Comment by Lindsayauchin** [comment]
what if we limit the icon set to the core set of resources bundled with Concourse?

**Comment by cirocosta** [comment]
Looking forward to 6.x where we might reduce significantly the number of resources we ship as core resources (see #3003), it seems like expanding that to custom resources would be a must 🤔 

It seems like having icons support would involve adding something like an `icon:` field somewhere like Helm charts do (https://github.com/helm/charts/blob/451214890c8138b48323449a414e54e6280f3b2c/stable/concourse/Chart.yaml#L5), which would mean having a new thing in the contract for resource implementors.

Would tooltips suffice? 😬

**Comment by osis** [comment]
I would personally be a fan of dynamic text over static or dynamic icons.

- My brain explodes just thinking of the UX of putting base64 image in my pipeline yaml. 
- I would hope we don't evolve the design so that spirit of creating resources and the culture of plug-ability isn't treated like a second-class citizen in the UI of Concourse.

**Comment by Lindsayauchin** [comment]
Tooltips would be the least disruptive to the current pipeline UI. 

Something like this?

screen shot 2019-02-07 at 2 50 38 pm

screen shot 2019-02-07 at 2 51 38 pm

**Comment by osis** [comment]
I'm a fan of tooltips! I think that should be posted as an alternate solution for the pipelines view issue (#788). This is about where to put that info on the resource details page.

If you feel like would be better to put this on the pipelines view and the same information doesn't belong on the details page. Then we should chuck this PR into the garbage.

giphy

I yield to your design wisdom @Lindsayauchin 🙇

**Comment by Lindsayauchin** [comment]
This tooltip could carry through to the resource page. 

screen shot 2019-02-07 at 6 07 54 pm

**Comment by osis** [comment]
I think that would be great for consistency, but I also feel like a resource details page should clearly display the critical information that people need to see.

In summary, I'm going to sit on this fence. 🤷‍♂️

**Comment by vito** [comment]
> My brain explodes just thinking of the UX of putting base64 image in my pipeline yaml.

Quick note: if/when we add support for this it would probably come from the resource type itself, perhaps from the `info` script in concourse/rfcs#1. I would rather not special-case core resources so having it part of the resource interface makes sense to me.

**Comment by vito** [comment]
@osis I'm gonna close this for now and put https://github.com/concourse/concourse/issues/788 on our radar with the short-term goal of just adding tooltips. I can reopen if ya want.

**Pull request closed without merging**
