### PR TITLE
Add test to ensure all routes are assigned to a role or admin only

### PR DESCRIPTION
**Pull request by clarafu**
# Why do we need this PR?
This PR adds a test to ensure that all routes are either assigned to a team role or is assigned to the admin only slice.

# Changes proposed in this pull request
The test within the accessor factory tests. 

Adding the test also found a few missing roles (GetWall and GetUser) so I assigned them to I role I found appropriate but I would like an extra check to make sure that they are assigned to the proper role (@pivotal-jwinters pls! :D)

Also removed some routes from the map that require admin privileges and added them to the AdminOnly slice.

# Contributor Checklist
> Are the following items included as part of this PR? Please delete checkbox items that don't apply.
- [x] Unit tests
- [ ] Integration tests (if applicable)
- [ ] Updated documentation (located at https://github.com/concourse/docs)
- [ ] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)

# Reviewer Checklist
> This section is intended for the core maintainers only, to track review progress. Please do not
> fill out this section.
- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the [BOSH](https://github.com/concourse/concourse-bosh-release) 
      and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not displayed in the `--help` text).

### CODE REVIEW

**Review by taylorsilva — DISMISSED** [review]
This is great! I did the minimum of adding a role to `routes.go` and the test failed as expected:

```
endpoint RoutesHaveRoles has no team or admin role
    Expected
        <[]string | len:6, cap:6>: [
            "GetLogLevel",
            "SetLogLevel",
            "ListActiveUsersSince",
            "InfoCreds",
            "SetWall",
            "ClearWall",
        ]
    to contain element matching
        <string>: RoutesHaveRoles
```

**Comment by taylorsilva** [comment]
I noticed that this PR was targeted to merge into #5257 which itself was already merged... not sure if we want to follow through with this or not.

**Comment by xtremerui** [comment]
@clarafu could you resubmit this PR against `master` branch?

**Comment by taylorsilva** [comment]
Don't think we're coming back to this and the conflicts seem real nasty now too.

**Pull request closed without merging**
