### PR TITLE
[skip-migrations-check] bump `secondary_order` migration

### PR DESCRIPTION
**Pull request by aoldershaw**
so that our smoke jobs can properly run them - the migrations got out of
order on master

Signed-off-by: Aidan Oldershaw <aoldershaw@pivotal.io>

[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

## What does this PR accomplish?

Bug Fix | Feature | Documentation

closes # .

## Contributor Checklist

- [ ] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [ ] [Signed] all commits
- [ ] Added tests (Unit and/or Integration)
- [ ] Updated [Documentation]
- [ ] Added release note (Optional)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

### CODE REVIEW

**Comment by taylorsilva** [comment]
Hmm maybe clearing out the smoke env is the better way to do this... https://ci.concourse-ci.org/builds/148878778#L609077eb:5
```
pr removed migrations:

1618347807_add_secondary_order_to_pipelines.down.sql

1618347807_add_secondary_order_to_pipelines.up.sql

and prs cannot remove migrations.
````

**Review by chenbh — APPROVED** [review]

**Comment by aoldershaw** [comment]
@taylorsilva yeah, maybe, don't have a preference, really - @clarafu mentioned she went with this approach before. I can bypass the check with `skip-migrations-check`

**Comment by chenbh** [comment]
What was the task originally supposed to guard against? I can see how removing a migration that already made it into a release will cause problems, but unreleased migrations should be fine no?

**Comment by aoldershaw** [comment]
Yeah, good point. Would probably be nicer if it just checked against the latest release tag rather than against `master` (for the "removal" of migrations - still want to use `master` for "out of order" migrations, though

**Pull request merged**
