### PR TITLE
Lftp resource

### PR DESCRIPTION
**Pull request by manno**
I created a custom resource which works with directory listings, using `lftp` gives access to various protocols like ftp, http, sftp and fish.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@manno Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/concourse&pullRequestId=1476)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/concourse&pullRequestId=1476) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by airtonix** [comment]
@mano shouldn't this just be a separate project released as a docker-image from your own dockerhub account?

**Comment by manno** [comment]
Hi @airtonix  this PR adds a link to the resource's Github page to the documentation. It also fixes the instructions on how to add community resources to the documentation, path was wrong.

The docker image is published at https://hub.docker.com/r/machinerytool/concourse-lftp-resource/

**Comment by vito** [comment]
This should be fine but needs some rebasing now. Mind updating it? Sorry for the delay!

**Comment by jtarchie** [comment]
Merged manually to resolve rebase. Thanks!

**Pull request closed without merging**
