### PR TITLE
experiment: add tracing to ATC

### PR DESCRIPTION
**Pull request by cirocosta**
Hey,

In https://github.com/concourse/concourse/pull/4247, I brought up that perhaps
we should not think of our metrics as events, but rather as indicators of
system status, but I didn't really went with a proposal for what could be the
thing that would let operators have something that resambles events (with very
precise timing, high cardinality, etc).

some time ago though, @njbennett had brought up something quite interesting
(https://github.com/concourse/concourse/issues/3958): Concourse could emit build
events as traces!

and, that's essentially what I tried implementing here, trying to be as neutral
as possible with regards to vendors by going straight with opentelemetry.

here's the result of this PR:

Screen Shot 2019-10-15 at 9 17 21 PM

*(yesterday, I demoed the PR to the team - here's where you can find what we talked about: https://ops.tips/notes/tracing-builds-concourse/)*

Although the PR does work (yeah, please, try it out!), my goal with this one is
to gather some thoughts from all of us to see whether that's something that we'd
like to do, think about possible problems, and ... just reason about it, thus,
marking it as "draft".

The PR is broken down in a series of commits that kinda tell a story:

- first, I implement a little wrapper on top of opentelemetry to shield
  ourselves from the changes that are constantly happening underneath
- then, subsequently, I wire that to the `web` command, so that one can
  configure it
- then, I keep adding tracepoints from the very high level build tracker down to
  container creation.

Please let me know what you think! I'm quite excited about the possibilities
here, and, if we do this right, I can see this being a big addition to
Concourse.

Thank y'all!

---

here's a sample `docker-compose.yml` that spins up 3 workers and has Jaeger set up: https://gist.github.com/cirocosta/6a676a071d64e0076a30139e76f46a74

### CODE REVIEW

**Comment by cirocosta** [comment]
If you want to try this out, here's a modified `docker-compose.yml` that you can use:

```yaml
version: '3'

services:
  db:
    image: postgres
    ports:
    - 6543:5432
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  web:
    build: .
    image: concourse/concourse:local
    volumes:
    - .:/src
    command: web
    depends_on: [db]
    ports:
    - 8080:8080
    environment:
      CONCOURSE_ADD_LOCAL_USER: test:test,guest:guest
      CONCOURSE_CLUSTER_NAME: dev
      CONCOURSE_CONTAINER_PLACEMENT_STRATEGY: random
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_PASSWORD: dev
      CONCOURSE_POSTGRES_USER: dev
      CONCOURSE_TRACING_JAEGER_COMPONENT: atc
      CONCOURSE_TRACING_JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  worker1: &worker-config
    build: .
    image: concourse/concourse:local
    command: worker
    privileged: true
    depends_on: [web]
    stop_signal: SIGUSR2
    environment: &worker-env
      CONCOURSE_BAGGAGECLAIM_BIND_IP: 0.0.0.0
      CONCOURSE_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_BIND_IP: 0.0.0.0
      CONCOURSE_TAG: common,worker1
      CONCOURSE_TSA_HOST: web:2222
  worker2:
    <<: *worker-config
    environment:
      <<: *worker-env
      CONCOURSE_TAG: common,worker2
  worker3:
    <<: *worker-config
    environment:
      <<: *worker-env
      CONCOURSE_TAG: common,worker3

  jaeger:
    image: jaegertracing/all-in-one:1.14
    command:
      - --sampling.strategies-file=/etc/jaeger/sampling_strategies.json
      - --log-level=debug
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - '14268:14268'
      - '25000:16686'
      - '5775:5775/udp'
      - '5778:5778'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '9411:9411'
```

**Comment by njbennett** [comment]
Where does this leave PR #4598?

I want to be able to view trace events data in Honeycomb in particular, because as far as I know this is the only system that lets me attach arbitrary fields of arbitrarily high cardinality to events. Traces let me understand how individual pieces of work flow through the system, but what I'm really looking for is "needles in a haystack full of needles" -- I want to be able to view all events of a particular type in aggregate, and then bucket them across arbitrary independent variables, to look for independent variables associated with anomalies.

I'm trying to answer questions like "why do certain resources sometimes stop triggering, and why does restarting the ATC fix that problem?" I'd like to be able to examine as many properties as possible of the events associated with resource triggering (and any other operation that exhibits odd behavior like that.)

It's unclear to me right now if Honeycomb is [compatible with the Open Telemetry standard yet.](https://docs.honeycomb.io/getting-data-in/open-tracing-open-census/) I might be able to hack it together even if it's not, but that would mean spending some time getting that working, rather than working on improving the contents of the events and traces Concourse is emitting.

The other path forward would be to merge my PR so I can continue to experiment with Honeycomb instrumentation, with the intention of rolling whatever work I do there into the Open Telemetry compatible emission path, whenever Honeycomb gets compatibility there fully online.

Let me know which path you'd like me to pursue @cirocosta @vito. I probably won't be back on this in earnest until November 8th, but I'd like to be able to do the work to get some data into Honeycomb at that point and start thinking about what else might be useful to emit.

**Comment by njbennett** [comment]
In general though-- I'm real pleased to see the vision @vito 's laid out above -- my main problem with Concourse right now is that I can't always understand what's happening inside of it when something goes wrong, but I think the technology is available now to give operators a "pane of glass" view of the operations of the entire system.

In my experience--
Events and traces are great for getting a high level view of the entire system at once, critical for the early stages of debugging distributed systems, and for finding problems you didn't even know were happening. The big drawback with them is that the datasets tend to be extremely large because they're optimized for understanding, not long term storage.

Logs are useful for understanding the exact chain of events on a specific node, or a small number of nodes. They're also handy for storing audit events for long periods of time. Human readability is really important in both cases.

Metrics are key for understanding whether problems that you know a lot about already are happening.

I'd love to see Concourse be able to emit some really rich events and traces, and let metrics and logs focus on being good at what they're good at, rather than first-line debugging tools.

**Comment by vito** [comment]
@njbennett Cheers for the feedback! These are all pretty high-impact things involving a lot of mechanical labor to change so it's good to hear signs of alignment from the community before we commit.

For Honeycomb, it sounds like you're in a similar position to me where I'd like to have support for emitting to DataDog APM which doesn't seem to have a native OpenTelemetry exporter yet. However they both have OpenCensus implementations, which seem to fit a very similar interface to `export.SpanSyncer` which is returned [here](https://github.com/concourse/concourse/pull/4607/files#diff-b534cb8961fd591806fdaa3a112e6498R24), so I bet we could easily add our own wrappers which use them under the hood:

* OpenCensus: [`trace.Exporter`](https://godoc.org/go.opencensus.io/trace#Exporter) and [`trace.SpanData`](https://godoc.org/go.opencensus.io/trace#SpanData)
* OpenTelemetry: [`export.SpanSyncer`](https://godoc.org/go.opentelemetry.io/sdk/export#SpanSyncer) and [`export.SpanData`](https://godoc.org/go.opentelemetry.io/sdk/export#SpanData)
* [Honeycomb implementation](https://godoc.org/github.com/honeycombio/opencensus-exporter/honeycomb#Exporter.ExportSpan)
* [DataDog implementation](https://godoc.org/github.com/DataDog/opencensus-go-exporter-datadog#Exporter.ExportSpan)

In comparing the two `SpanData` structs, though, it looks like OpenTelemetry has dropped the `Annotations` field, which is unfortunate since that sounds like the part you care the most about. With OpenTelemetry being the eventual successor to OpenCensus (as far as I'm aware) I'm not sure if you'll have much choice in the long run. :thinking: I wonder if they replaced that with something else, or if they dropped it? (Or maybe `Attributes` replaces it? I see it's in both - maybe `Annotations` was deprecated in OpenCensus and dropped in OpenTelemetry?)

**Comment by marco-m** [comment]
@cirocosta Yes man. You showed that I was not the only one dreaming this. Thank you.

**Comment by cirocosta** [comment]
[ipm]: (a reminder for me):

- add release notes
- add docs mentioned the experimental state of this
- check if there's anything left that would prevent this from being merged

**Comment by cirocosta** [comment]
Hey,

two updates:

1. bumped `opentelemetry-go` to v0.1.0 - their first release (from 6 days ago
   :grin:)

2. added a benchmark to ensure that we're close to a zero-cost abstraction
   ("what you don't use, you don't pay; what you use, you couldn't handcode any
   better") - more specfically w/ regards to the "you don't pay if you don't
   use".


`1` was a matter of updating the tracer registration, and the imports.
`2` was all about us providing the `NoopSpan` when not registered.

The reason for not going with just their NoopTracer is that the library goes
ahead w/ growing the `context` that you provide to it, which turns into 1
alloc per op.

E.g., for a random call to `StartSpan`, we can see that we get to `context.WithValue`:

        context.WithValue
            at /usr/local/go./context/context.go:487
        go.opentelemetry.io/otel/api/trace.SetCurrentSpan
            at /go/pkg/mod/go.opentelemetry.io/otel@v0.1.0/api/trace/current.go:28
        go.opentelemetry.io/otel/api/trace.NoopTracer.Start
            at /go/pkg/mod/go.opentelemetry.io/otel@v0.1.0/api/trace/noop_trace.go:50
        go.opentelemetry.io/otel/api/trace.(*NoopTracer).Start
            at <autogenerated>:1
        github.com/concourse/concourse/atc/tracing.StartSpan
            at ./atc/tracing/tracer.go:55


Thus, here's how it looked before (using the NoopTracer):


        goos: darwin
        goarch: amd64
        pkg: github.com/concourse/concourse/atc/tracing
        BenchmarkNoTracing-12               33.2 ns/op     0 B/op   0 allocs/op
        BenchmarkNoopTracer-12              84.1 ns/op    48 B/op   1 allocs/op
        BenchmarkNoopTracerWithAttrs-12      193 ns/op    96 B/op   2 allocs/op


             flat  flat%   sum%        cum   cum%
          672.53MB   100%   100%   672.53MB   100%  context.WithValue
                 0     0%   100%   672.53MB   100%  github.com/concourse/concourse/atc/tracing.StartSpan
                 0     0%   100%   672.53MB   100%  github.com/concourse/concourse/atc/tracing_test.BenchmarkNoopTracer
                 0     0%   100%   672.53MB   100%  github.com/concourse/concourse/atc/tracing_test.noop
                 0     0%   100%   672.53MB   100%  go.opentelemetry.io/otel/api/trace.NoopTracer.Start
                 0     0%   100%   672.53MB   100%  go.opentelemetry.io/otel/api/trace.SetCurrentSpan


        Total: 672.53MB
                 0   672.53MB (flat, cum)   100% of Total
                 .          .     50:func StartSpan(
                 .          .     51:   ctx context.Context,
                 .          .     52:   component string,
                 .          .     53:   attrs Attrs,
                 .          .     54:) (context.Context, trace.Span) {
                 .   672.53MB     55:   ctx, span := global.TraceProvider().GetTracer("atc").Start(
                 .          .     56:           ctx,
                 .          .     57:           component,
                 .          .     58:   )
                 .          .     59:


        Total: 672.53MB
          672.53MB   672.53MB (flat, cum)   100% of Total
                 .          .    482:           panic("nil key")
                 .          .    483:   }
                 .          .    484:   if !reflectlite.TypeOf(key).Comparable() {
                 .          .    485:           panic("key is not comparable")
                 .          .    486:   }
          672.53MB   672.53MB    487:   return &valueCtx{parent, key, val}
                 .          .    488:}
                 .          .    489:
                 .          .    490:// A valueCtx carries a key-value pair. It implements Value for that key and
                 .          .    491:// delegates all other calls to the embedded Context.
                 .          .    492:type valueCtx struct {


By shortcircuiting that entirely (with a `tracing.Configured`) variable, we're
then able to avoid all of that, which brings us down to 0 allocs:

        goos: darwin
        goarch: amd64
        pkg: github.com/concourse/concourse/atc/tracing
        BenchmarkNoTracing-12                33.2 ns/op  0 B/op    0 allocs/op
        BenchmarkNoopTracerWithAttrs-12      55.5 ns/op  0 B/op    0 allocs/op
        BenchmarkNoopTracer-12               37.0 ns/op  0 B/op    0 allocs/op

**Comment by cirocosta** [comment]
Superseded by https://github.com/concourse/concourse/pull/5043

Thanks!

**Pull request closed without merging**
