### PR TITLE
Add --team to fly commands

### PR DESCRIPTION
**Pull request by owenfarrell**
## What does this PR accomplish?

Feature

## Changes proposed by this PR:

* Add `--team` flag for `fly pause-pipelines` command
* Add `--team` flag for `fly hide-pipeline` command

## Release Note

* Add `--team` flag for `fly pause-pipeline` command
* Add `--team` flag for `fly hide-pipeline` command

## Notes to reviewer:

The... healthy amount of whitespace change to `fly/integration/pause_pipeline_test.go` is because there was a test outside of the `Describe` block.

## Contributor Checklist
- [x] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [x] [Signed] all commits
- [x] Added tests (Unit and/or Integration)
- [x] Updated [Documentation]
- [x] Updated [Release notes]

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs
[Release notes]: https://github.com/concourse/concourse/tree/master/release-notes

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the [BOSH](https://github.com/concourse/concourse-bosh-release) and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not displayed in the `--help` text).

### CODE REVIEW

**Comment by owenfarrell** [comment]
@aoldershaw - Thanks for the review!

For that 1 PR check, I assumed that it flaked. But when I try to view the job, I just get a spinning wheel. So if there is something legitimate there, I might need some help getting the failure details.

**Comment by aoldershaw** [comment]
@owenfarrell looks like it was just a flake, as it passed the second time around. You should have been added to the contributors team after opening a PR, which has access/rerun the PR builds 🤷

**Comment by aoldershaw** [comment]
Just sent you an invite to the @concourse/contributors team

**Comment by owenfarrell** [comment]
@aoldershaw - Thanks!

FWIW - when trying to access the link from the PR (which includes the `BUILD_ID` as a path parameter), I get the spinning wheel. But I can browse via the main screen to the `pr` pipeline and view the job history no problem... just means I have to walk my way back through history to see what version triggered _**this**_ PR build.

Not sure if there's an ops issue there that needs some attention. 🤷‍♂️

**Comment by aoldershaw** [comment]
Huh, interesting. We'll take a look

**Comment by owenfarrell** [comment]
That did the trick - thanks!

Root cause: I was getting a 403 on the API call (e.g. https://ci.concourse-ci.org/api/v1/builds/2028256)

**Pull request merged**
