### PR TITLE
WIP: remove global mutex from lock.go

### PR DESCRIPTION
**Pull request by evanchaoli**
[add yourself]: https://github.com/concourse/governance#individual-contributors
[PR requirements]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md#pull-request-requirements

## Changes proposed by this PR

closes # 

* [x] done
* [ ] todo

## Release Note

* 

[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

### CODE REVIEW

**Comment by clarafu** [comment]
Hmm I think I know what the `acquireMutex` lock is for. 

https://github.com/concourse/concourse/blob/1b1dc768fd4fe124c5fde7ed82ee867954e15dc8/atc/db/lock/lock.go#L165-L166 

I think this is for making sure we don't have two threads trying to acquire the same lock at the same time. This is because if two threads try to acquire the same advisory lock (in the same session), they both will be able to acquire it. That is why we check if the lock is registered in the `lockRepo` in order to know if we have already acquired this lock https://github.com/concourse/concourse/blob/1b1dc768fd4fe124c5fde7ed82ee867954e15dc8/atc/db/lock/lock.go#L170-L173 because if we try to acquire the same lock again in the same session, it will successfully acquire. But if the two threads kick off at the same time, both will check that the lock is unregistered and then both select the advisory lock from postgres and both will be successful (which we don't want).

**Comment by evanchaoli** [comment]
@clarafu You are right, as a lock factory use a single db connection, a mutex is needed to prevent multiple threads from acquiring the same advisory lock. But the mutex doesn't have to be a global one. When a build is trying to acquiring a creating-volume-lock, why it needs to wait for lidar scanner to acquire lidar-scanner-lock? Thus, from my test result, the global lock more like to slow down an ATC so that other ATC may share workloads.

In theory, each lock may use a separate mutex, but given the total amount of locks holding, there will be too many mutexes which is also costly. Given there is single db connection for lock factory, acquiring lock has to be in serial. We can use a db connection and a mutex for a type of locks, which is code change I proposed in this PR.

But from my observation over our prod cluster, the bottleneck is currently not at db-lock. So we don't have to patch 6.x with this lock change. For 7.x, I think this is still needed. I will raise a separate PR for the lock change on master branch.

**Comment by clarafu** [comment]
I see, that definitely makes sense to have the mutex be on the lock type. 👍 

Unfortunately, I don't think we will be doing any further patches to the 6.7.x series because of our limited staff and all our efforts are focused on getting a stable version of 7.x series. Would you be comfortable with us working towards releasing a more stable version of the 7.x series and using that to upgrade runway?

**Comment by clarafu** [comment]
I'm going to close this because we are not going to be doing any patches for 6.7.x series! https://github.com/concourse/concourse/pull/8198 is the same changes but on master branch

**Pull request closed without merging**
