### PR TITLE
Fix missed check notifications

### PR DESCRIPTION
**Pull request by clarafu**
If the interval runner is not started up yet and we send a notification
to check a resource, the notification gets lost. This PR adds a
safeguard by having a condition notifier that will check a check
requested time value on the resources table to confirm whether or not we
need to run a check.

The resource type object was given the same notifier methods but are not used in order to maintain consistency between the two.

[#3759]

### CODE REVIEW

**Comment by pivotal-jamie-klassen** [comment]
@clarafu can you rebase this? looks like the pr-resource [here](https://ci.concourse-ci.org/teams/main/pipelines/prs/resources/concourse-pr) missed or forgot this version.

**Comment by clarafu** [comment]
@pivotal-jamie-klassen Okk, I rebased it!

**Comment by vito** [comment]
@clarafu Looks like a migration snuck in to `master`, could you bump the migration number and re-push?

**Comment by vito** [comment]
Actually after chatting with @pivotal-jwinters and @clarafu this is being superceded by #3788 - closing!

The plan is to use the new check queue for manually queued `check`s (`fly check-resource` and manually triggered jobs), and have a feature-flag for whether we rely on it for mission-critical continuous resource checking until we see it going well in production environments.

**Pull request closed without merging**
