### PR TITLE
Restart TSA if it's leaking memory

### PR DESCRIPTION
**Pull request by tushar-dadlani**
This mitigates https://github.com/concourse/concourse/issues/879 , while a fix is developed.

### CODE REVIEW

**Comment by voelzmo** [comment]
ouch, brutal.

**Comment by dsharp-pivotal** [comment]
Brutal? If the process is mis-behaving, this seems like a good safeguard. Even in the absence of #879, I think this is a good idea.

**Comment by schubert** [comment]
@vito given this is a cheap safeguard to at least mitigate the problem any reason this couldn't make it into 2.7.1 while the root cause of #879 is figured out?

**Comment by chendrix** [comment]
Hi all, we believe we've figured out and fixed #879 which will be included in 2.7.1

Because of that, I'd prefer to kick the can down the road a little bit and not add this into our monit file until we've had a larger discussion about our theme "Efficiency". As such, I'm closing this but I'm tagging the tracker story with `efficiency`.

**Pull request closed without merging**
