### PR TITLE
web: fix layout of resource boxes on pipeline view

### LINKED ISSUE #3224: Pinned Resource Hover Style
When a resource has a pinned version, hovering over it in the pipeline view removes the padding between the pin icon and the text.

resource

* Concourse version: dev
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: local
* Browser (if applicable): Chrome
* Did this used to work? N/A

### PR DESCRIPTION
**Pull request by pivotal-jamie-klassen**
fixes #3224

### CODE REVIEW

**Comment by pivotal-jamie-klassen** [comment]
Trying to do this the Right Way on the `js-unit-tests` branch and realizing that it is pretty tricky to 'observe' (via DOM or SVG query methods, i.e. [getBBox](https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement), [clientWidth](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientWidth), [scrollWidth](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollWidth), [getBoundingClientRect(...).width](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) or [window.getComputedStyle(...).width](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle)) the effect of an SVG filter (`dilate` in our case, via the [`#embiggen` element](https://github.com/concourse/concourse/blob/73221b3d902c1e5ed13296784163e93cc7129b1b/web/public/index.js#L268-L272)): long story short, almost all of the existing methods will only query the dimensions of an element _independent_ of its applied filters/transforms. This seems like a [reasonably well-established problem](https://stackoverflow.com/questions/9847684/get-the-real-size-of-a-svg-g-element) and while there may be tricks by which you can compute the resulting dimensions of an SVG element after it has a filter applied, it seems likely to be hard to reason about. From a pure TDD perspective this would discourage using filters at all, but maybe there's a way to think about the layout such that the `dilate` filter can be used alongside the required size/position changes for the text and pin icon. For now, I think we can agree that this is a magic number smell:

https://github.com/concourse/concourse/blob/master/web/assets/css/production.less#L347

**Comment by vito** [comment]
@pivotal-jamie-klassen fyi this is kind of a small polish thing so I'm gonna take it out of the 5.0 milestone.

**Comment by vito** [comment]
Just came back and took a look at this and it seems pretty broken (probably due to recent changes for resource icons). Do we still need this? It seems like the resource boxes are rendering OK now.

**Comment by pivotal-jamie-klassen** [comment]
I'm fine closing this now. There's a better effort on the `js-unit-tests` branch anyway, which I might come back to at some point.

**Pull request closed without merging**
