### PR TITLE
topgun/k8s: New External workers functionality

### PR DESCRIPTION
**Pull request by YoussB**
- This fixes the team external workers test after merging helm/charts#12056

Signed-off-by: Bishoy Youssef <byoussef@pivotal.io>

### CODE REVIEW

**Comment by cirocosta** [comment]
Seems good! I left some comments there in the upstream PR 👍

**Comment by cirocosta** [comment]
https://github.com/helm/charts/pull/12056 just got in!

Now, this one just needs to update the keys 👍

**Comment by YoussB** [comment]
Hey @cirocosta, Key updated.

**Comment by YoussB** [comment]
Had to pin the PR to make sure the unit test runs on it 😁

**Pull request merged**
