### PR TITLE
Add additional parameter to oidc SkipEmailVerified to translate it to the dex

### PR DESCRIPTION
**Pull request by kirillbilchenko**
Explanation of issue can be found in this PR: [dex](https://github.com/dexidp/dex/pull/1417)

Add `--oidc-force-email-verified` flag to OIDC connector configure.

As we are using Azure as an identity provider, it's not producing this field. 
Some providers return claims without "email_verified", when they had no usage of emails verification in enrollement process.

Signed-off-by: kirillbilchenko <kirya7@gmail.com>

[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

## What does this PR accomplish?

Bug Fix | Feature | Documentation

closes # .

## Release Note
Fixing issue when identity provider is not issuing this flag, and there is no way to override it on IDP side.

## Contributor Checklist

- [x] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [x] [Signed] all commits
- [ ] Added tests (Unit and/or Integration)
- [x] Updated [Documentation]
- [x] Added release note (Optional)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

### CODE REVIEW

**Comment by xtremerui** [comment]
For a temporary solution, https://github.com/concourse/concourse/issues/6431#issuecomment-768336133

**Review by chenbh — APPROVED** [review]
lgtm, @kirillbilchenko you might also want to open an identical PR to backport this to the `release/v6.7.x` branch, `master` is currently targeted for v7.0.0.


@xtremerui what do you think of allowing configuring an `--dex-config` flag which gets marshalled into an `oidc.Config` struct and then merged with the config we construct?
 
The idea would be that if dex decides to add any new flags that we didn't notice, users can at least work around the regression without having to wait for a patch release.

**Review by chenbh — CHANGES_REQUESTED** [review]
Actually, do you mind renaming the flag to `InsecureSkipEmailVerified`? It better describes what it actually does: ignore the `email_verified` value

**Comment by xtremerui** [comment]
> @xtremerui what do you think of allowing configuring an `--dex-config` flag which gets marshalled into an `oidc.Config` struct and then merged with the config we construct?

I think it could be an additional config to all cmds in skymarshall so it will work for all connectors.

**Comment by kirillbilchenko** [comment]
> Actually, do you mind renaming the flag to `InsecureSkipEmailVerified`? It better describes what it actually does: ignore the `email_verified` value

will rename, @chenbh I will open the same PR to backport branch after we will merge this one

**Review by chenbh — APPROVED** [review]

**Pull request merged**
