### PR TITLE
Initial Services RFC Implementation

### PR DESCRIPTION
**Pull request by jryan128**
[add yourself]: https://github.com/concourse/governance#individual-contributors
[PR requirements]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md#pull-request-requirements

## Changes proposed by this PR
Start to Implement the [Services RFC](https://github.com/concourse/rfcs/pull/84).

I created this PR to get feedback on the implementation before working the
rest of the TODO items below:

* [x] Start/stop services with task
* [ ] Add events in task_delegate for services
* [ ] UI changes, service UI will be like task but as a substep of task, mockup:
* [ ] Startup Probe
* [ ] containerd implementation
* [ ] Write tests, examples, documentation

Services UI mockup:
image

## Notes to reviewer

To reiterate, I only started the implementation because I wanted to get feedback on the implementation before working the
rest of the TODO items above. Thanks!!

## Release Note

[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

### CODE REVIEW

**Comment by jryan128** [comment]
I can definitely redo the Git history and break it into parts if you wish. I just want some initial feedback on the approach before putting more work into it. Thanks!

**Comment by xtremerui** [comment]
hi thx for picking this up! For whoever interested at this RFC please feel free to leave you comment so we work together to bring this great feature to live.

**Comment by xtremerui** [comment]
@jryan128 I am so sorry that I missed your pin and only found out until now. There have been lots of stuff going on in the team so we can't pick it up still. However I do appreciate your work and hope it can be kept.

Is it possible for you to continue while things are moving? Thank you!

**Comment by jryan128** [comment]
We're moving to GitHub actions now, so I won't be able to to continue with
it. Sorry 😔. You're free to take the PRs if they are helpful at all.

**Pull request closed without merging**
