### PR TITLE
Change default container placement strategy to fewest build containers

### PR DESCRIPTION
**Pull request by kcmannem**
Depends on #3301 

Co-authored-by: Krishna Mannem <kmannem@pivotal.io>

### CODE REVIEW

**Comment by ddadlani** [comment]
#3301 has been merged, once the modified topgun test passes this should be ok to merge

**Comment by kcmannem** [comment]
with volume streaming being mostly free. The importance of volume locality is reduced largely. We should now use fewest-build-containers to balance load appropriately on default.

**Comment by kcmannem** [comment]
kicked off the tests again, they should pass and this is ok to merge since volume changes are in now.

**Comment by kcmannem** [comment]
Ready to go in

**Comment by wagdav** [comment]
I believe this strategy is a better default than the volume locality.  However, #3301 is still open. My understanding is that currently only the `limit-active-task` strategy provides race-free worker selection.

**Comment by nader-ziada** [comment]
@kcmannem  is there anything holding this back from being merged?

**Comment by kcmannem** [comment]
@nader-ziada just waiting on someone other than me to merge it in. Feel free to approve/merge.

**Comment by ddadlani** [comment]
Hi @wagdav you are correct, the race issue is still present, but we feel that `fewest-build-containers` is the most general solution we have right now. Even with the race condition, average utilization with `fewest-build-containers` is better than `volume-locality`, which is the current default.

**Comment by ddadlani** [comment]
we're not going to switch to this right now, we're going to wait for a more correct solution for fewest-build

**Pull request closed without merging**
