### PR TITLE
Document quickstart bosh release

### PR DESCRIPTION
**Pull request by roobert**
Today I wanted to customise some of the CSS in ATC and being new to Bosh and unfamiliar with the concourse code base this took a bit of working out. I thought others may benefit from this process being documented.

I'm not sure if the README is the best location for this information so please let me know if I should move it.

Thanks for the great software!

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@roobert Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/concourse&pullRequestId=859)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/concourse&pullRequestId=859) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@roobert Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/concourse&pullRequestId=859)!

**Comment by vito** [comment]
Did you see https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md ?

**Comment by roobert** [comment]
@vito, hi, I didn't see those docs so thanks. I spoke to one of the devs on slack who said that a quick start section would be a good idea (I think my instructions are a bit simpler for the layperson than the ones in CONTRIBUTING) -- do you not want to duplicate content? Could we maybe merge these docs into CONTRIBUTING? I think it'd also be a good idea to link to CONTRIBUTING from the README and explain that there are instructions in there which relate to how to build the project (as it's not immediately obvious).

Cheers,

**Comment by chendrix** [comment]
I worry about documentation about how to get development dependencies going out of date. Even this documentation tells people to install go1.7.4

I want to capture your use case though, so even though I'm closing this PR I'm going to tag the tracker story with `docs` so we can keep track of it when we review our documentation.

Thanks again for your contribution, I hope you keep contributing to concourse!

**Pull request closed without merging**
