### PR TITLE
Add list of known resources to docs.

### PR DESCRIPTION
**Pull request by jchesterpivotal**
Credit to @arondeau and @skmichaelson as coauthors.

### CODE REVIEW

**Comment by jchesterpivotal** [comment]
We were [unable to build these docs locally](https://github.com/concourse/concourse/issues/237), so this patch might not build.

**Comment by xoebus** [comment]
@jchesterpivotal I'd like to merge this. Could you re-open this against the `develop` branch please?

**Comment by xoebus** [comment]
Actually, nevermind - I'll merge manually.

**Comment by xoebus** [comment]
Merged as https://github.com/concourse/concourse/commit/c49a87470de529ae287b95b22ff6b394f9079c86.

Thanks!

**Comment by jchesterpivotal** [comment]
Sorry that I was away, but thanks very much for accepting the PR!

**Pull request closed without merging**
