### PR TITLE
Add worker flag to configure container network pool

### LINKED ISSUE #5140: containerd: make container subnet configurable
### what challange are you facing

it's imposssible to tweak the subnet that the containers we create use.

despite us having `CNINetworkConfig` configurable, it's currently using a
default config that never gets modified - there are no flags to allow that to
happen (despite an option - `WithCNINetworkConfig` - existing)

https://github.com/concourse/concourse/blob/54991b2f1f17bd7d229a3ebbe6d6c16f3ff495a3/worker/backend/cni_network.go#L37-L41
https://github.com/concourse/concourse/blob/54991b2f1f17bd7d229a3ebbe6d6c16f3ff495a3/worker/backend/cni_network.go#L55-L84

### what would make this better

have a way of letting an operator configure the parameters used for setting up
the CNI network.

### PR DESCRIPTION
**Pull request by xtremerui**
# Existing Issue
Fixes #5140  .

# Changes proposed in this pull request
add `container-network-pool` flag to worker command. It will be passed to garden server flag `network-pool` or containerd cni network config.

The env var will be `CONCOURSE_CONTAINER_NETWORK_POOL`

# Contributor Checklist
- [ ] Unit tests
- [ ] Integration tests (if applicable)
- [ ] Updated documentation (located at https://github.com/concourse/docs)
- [ ] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)

# Reviewer Checklist
- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] Bosh release update
- [ ] Concoures chart update

### CODE REVIEW

**Comment by vito** [comment]
There's an interesting failure in `testflight-containerd` on [this line](https://ci.concourse-ci.org/builds/965391#L5e871025:3119):

```
    initializing
    running echo pass
    pass
    initializing
    running echo passing job on success
    passing job on success
    initializing
    running echo passing job ensure
    Backend error: Exit status: 500, message: {"Type":"","Message":"proc start: failed to start console copy: context deadline exceeded","Handle":"","ProcessID":"","Binary":""}
    
    initializing
    running echo passing job on job error
    passing job on job error
    initializing
    running echo passing job on job ensure
    passing job on job ensure
    errored
```

Looks like it could be a flake? Do we have some sort of timeout on process starting that we need to relax?

**Comment by xtremerui** [comment]
Looking at the builds of testflight-containerd it does feel like there are more failures than other test jobs in general.

**Comment by muntac** [comment]
hmm looks like it got especially bad since build [353](https://ci.concourse-ci.org/teams/main/pipelines/prs/jobs/testflight-containerd/builds/353). also both that and watjs stuck in pending right now.

**Comment by muntac** [comment]
Have tried rerunning the builds in `testflight-containerd` but they keep getting stuck in pending. Not sure of how to get them unstuck. I think #5475 is an attempt to fix this.

**Comment by xtreme-sameer-vohra** [comment]
Based on the discussion in https://github.com/concourse/concourse/issues/5140#issuecomment-619029015 
`CONCOURSE_CONTAINER_NETWORK_POOL` shouldn't work for garden but if this env var is set, it does configure the network for garden.

`CONCOURSE_GARDEN_NETWORK_POOL` also works for garden. Based on the code it shouldn't work for containerd. 

Overall, I don't anticipate that this is an issue right now, however, we'd want to make sure it is addressed before support for `containerd` is GA

**Pull request merged**
