### PR TITLE
Documentation changes

### PR DESCRIPTION
**Pull request by zachgersh**
i made a mistake in the last pull-request.

Reopened here.  Right sort of changes.

Sorry @vito

### CODE REVIEW

**Comment by zachgersh** [comment]
Will grab comments from #37 - no need to make them again here.

**Comment by devcurmudgeon** [comment]
I'd recommend merging this as it is - perfect is the enemy of the good :)

**Comment by zachgersh** [comment]
@devcurmudgeon - thanks for the feedback!  I've got a couple great suggestions from @vito to implement and then I think we'll be well on our way to getting this merged this week.

**Comment by zachgersh** [comment]
@vito - all your feedback should be account for.  Should be good to merge if you are happy.

**Comment by devcurmudgeon** [comment]
s/Concourse welcomes pull-request on any one of the many open-source/Concourse welcomes pull-requests on any of the many open-source/

**Pull request merged**
