### PR TITLE
AWS SecretsManager can be used from var_sources

### PR DESCRIPTION
**Pull request by PG2000**

### CODE REVIEW

**Review by clarafu — APPROVED** [review]
It looks good, thanks for the PR!

I'm sorry for the delay in reviewing, could you quickly resolve the conflicts with `master`? It should be a very easy change of just adding the mapstructure to the `SharedSecretTemplate` that was newly added and then setting the `DefaultSharedSecretTemplate` in the construction of the manager. Thanks so much!

**Comment by PG2000** [comment]
> It looks good, thanks for the PR!
> 
> I'm sorry for the delay in reviewing, could you quickly resolve the conflicts with `master`? It should be a very easy change of just adding the mapstructure to the `SharedSecretTemplate` that was newly added and then setting the `DefaultSharedSecretTemplate` in the construction of the manager. Thanks so much!

Sure. I've done that. Thx for reviewing

**Review by clarafu — APPROVED** [review]
Thanks! :)

**Comment by PG2000** [comment]
@clarafu any chance to get this in the next release?

**Comment by clarafu** [comment]
Yup! I think it can be in 7.7

**Pull request merged**
