### PR TITLE
Allow filtering by exact match on the dashboard by quoting search terms

### LINKED ISSUE #3010: Filter by teams not exact match
## Bug Report

When you filter by team concourse also displays teams whose name "contains" the selected team name.

I think when using the qualifier `team:` then the results should only include exact matches to team name.

It's surprising that after selecting from a drop-down list, effectively saying I want pipelines for "teamX", to get also all other teams that contain "teamX" in their name.

## Steps to Reproduce

1. Create a team "team-one"
2. Create a team "team-one-two"
3. Add user to both teams
4. Select `team: team-one` search

## Expected Results

Only `team-one` pipelines shown

## Actual Results

Both `team-one` and `team-one-two` pipelines are shown

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): binary
* Browser (if applicable): Firefox 64.0
* Did this used to work? Not sure

### PR DESCRIPTION
**Pull request by aoldershaw**
[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

## What does this PR accomplish?

Bug Fix | **Feature** | Documentation

closes #3010 .

## Changes proposed by this PR:

* Wherever a string term is accepted in the dashboard search bar (team name, pipeline name), allow quoting the term to force an exact match
  * e.g. `team: team` will match `team`, `team1`, `other-team`, `tremendous-and-magnificent`, as it uses fuzzy matching
  * `team: "team"` will only match `team`
* When a term has partial quotes (e.g. `"team`), it checks the prefix of strings
  * e.g. `team: "team` will match `team`, `team1`
  * When you're typing out the filter, and have the opening quote, it doesn't make sense to do an exact match, since everything will disappear until you finish what you're typing
* Teams that appear in the search dropdown are quoted, since if you're selecting a team from the dropdown, you probably want an exact match

## Contributor Checklist

- [ ] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [ ] [Signed] all commits
- [ ] Added tests (Unit and/or Integration)
- [ ] Updated [Documentation]
- [ ] Added release note (Optional)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

### CODE REVIEW

**Comment by aoldershaw** [comment]
Marking as blocked on #6105 - it's technically not blocked, but filtering by exact pipeline name won't work once it's merged, and I'd rather solve that in this PR than add more onto the already massive instanced pipelines UI one.

**Review by chenbh — CHANGES_REQUESTED** [review]
Nit: it doesn't seem to like search queries with leading spaces in them. It should either be so strict it shows no matches, or lax enough that it trims any leading spaces.

**Comment by chenbh** [comment]
I'm not sure how relevant this would be once we start enforcing valid identifiers, but the UI seems to handle pipeline names with `"` or leading spaces in them poorly.
- leading spaces are trimmed when displaying so we can have multiple non-instance pipelines with the same name. These pipelines are actually named "foo", " foo", and " 
 foo"
image
- pipelines that contains quotes in the name actually causes a console error and kinda locks up the ui when you hover over the card

**Comment by aoldershaw** [comment]
@chenbh we fixed the issue with leading spaces

I'm inclined to just ignore issues that come from pipelines with leading/trailing spaces or `"` in the name - we give a warning anyway (and soon will enforce it, as you note), and I'm doubtful that many people are naming their pipelines like that

**Review by chenbh — APPROVED** [review]
lgtm

**Comment by aoldershaw** [comment]
closing in favour of #6433, which contains this PR

**Pull request closed without merging**
