### PR TITLE
atc: add global step timeout

### PR DESCRIPTION
**Pull request by christophermancini**
We have the shared the same pain as @kmacoskey in #2341, with tasks that can go unnoticed and running for days / weeks. I have created reports to help us catch jobs that have been running longer than 2hrs but I would prefer to have Concourse kill these tasks themselves.

This PR potentially resolves this issue by allowing the operator to set a `GlobalStepTimeout` on the web node, which defaults to `0s`.

### CODE REVIEW

**Comment by kmacoskey** [comment]
+1 I fully support this. It is still an issue we have.

**Comment by christophermancini** [comment]
I still need to finish the tests which I will be able to circle back to within the next few days.

**Comment by christophermancini** [comment]
@vito I haven't been able to circle back to it as I am up against a big deadline to move all of our servers off of trusty to bionic. I should be done with that work within the next week or two and then I can finish up the tests, which is creating a test case in `testflight`.

**Comment by vito** [comment]
@christophermancini Sounds good. FWIW I don't think we need a testflight test for this, since it depends on operator configuration and Testflight doesn't have any control over that. A TopGun test, which you've already added, seems appropriate. :+1:

**Comment by christophermancini** [comment]
@vito oh, in that case, then this is good to go! minus the conflict that now exists. :(

**Comment by christophermancini** [comment]
@vito resolved the conflict, you are free to review

**Comment by xtremerui** [comment]
Hi @christophermancini are you still working on this PR? Thanks!

**Comment by kirillbilchenko** [comment]
@vito @xtremerui @christophermancini are you guys planning to address this pr in any way, I think it's really useful property, which can help stabilise execution.

**Comment by christophermancini** [comment]
@xtremerui @kirillbilchenko I intend to tackle this if no one gets to it first. Just have some higher priority things to attend to first. I should be able to get to it sometime in Q2.

**Comment by clarafu** [comment]
@christophermancini Hi! I'd like to close this PR for now because it has been almost a year with no activity. Please feel free to open a new PR if you ever get the chance to tackle this, thanks!

**Pull request closed without merging**
