### PR TITLE
concourse#5215 fly: add --team flag to set-pipelines

### PR DESCRIPTION
**Pull request by jroden**
document DCO process

Signed-off-by: jroden <joden1995@gmail.com>

## What does this PR accomplish?

Feature

closes # .

## Changes proposed by this PR:

Currently the only way for users to set pipelines from different teams with Fly is to create multiple targets. With this addition users can now set pipelines against different teams within a target. This is part of the #5215 checklist.

## Notes to reviewer:

First time contributor here, thanks for the help! :smile: Pretty straightforward addition code-wise.  For testing, can run the specific ginkgo case as needed with `ginkgo --focus='when setting new pipeline with non-default team'` 

## Contributor Checklist

- [x] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [x] [Signed] all commits
- [x] Added tests (Unit and/or Integration)
- [ ] Updated [Documentation]
- [ ] Updated [Release notes]

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs
[Release notes]: https://github.com/concourse/concourse/tree/master/release-notes

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

### CODE REVIEW

**Comment by xtremerui** [comment]
Hi thx for the PR. Could you add a release note for this feature?

**Comment by jroden** [comment]
Just added, good catch! :smile:

**Comment by jroden** [comment]
Rebased commits, added DCO :sweat_smile:

**Comment by xtremerui** [comment]
@jroden there is conlict in release-notes

**Comment by jroden** [comment]
Sorry!  figured that was one that could be manually resolved.  Just pulled upstream to resolve, let me know if there's anything else!

**Comment by jroden** [comment]
Just merged upstream to resolve the conflict-- let me know if there's anything else. Thanks!

**Pull request merged**
