### PR TITLE
web: behaviour: bump @mdi/svg 4.5.95 -> 5.0.45

### PR DESCRIPTION
**Pull request by pnsantos**
# Existing Issue

Fixes https://github.com/concourse/concourse/issues/5379

# Changes proposed in this pull request
> What are the changes included in this PR? Feel free to add as many lines as needed below.

* Updates `@mdi/svg` lib to provide access to newer icons

# Contributor Checklist
> Are the following items included as part of this PR? Please delete checkbox items that don't apply.
- [x] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)

# Reviewer Checklist
> This section is intended for the core maintainers only, to track review progress. Please do not
> fill out this section.
- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [x] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the [BOSH](https://github.com/concourse/concourse-bosh-release) 
      and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not displayed in the `--help` text).

### CODE REVIEW

**Comment by pn-santos** [comment]
Not really sure why `testflight-containerd` failed, https://ci.concourse-ci.org/teams/main/pipelines/prs/jobs/testflight-containerd/builds/201 shows success :confused:

**Comment by pnsantos** [comment]
Not really sure why `testflight-containerd` failed, https://ci.concourse-ci.org/teams/main/pipelines/prs/jobs/testflight-containerd/builds/201 shows success :confused:

**Comment by aoldershaw** [comment]
> Not really sure why `testflight-containerd` failed, https://ci.concourse-ci.org/teams/main/pipelines/prs/jobs/testflight-containerd/builds/201 shows success 😕

Whoops, seems like we had two pipelines running the `testflight-containerd` job, one of which should have been removed - I did that and re-triggered the job on the correct pipeline just so the PR will be green.

**Comment by aoldershaw** [comment]
Hmm...I realize that `@mdi/svg v5.0.45` renamed `mdi-github-circle` to `mdi-github`.  I imagine a lot of pipelines use `icon: github-circle` (many of [our pipelines](https://ci.concourse-ci.org/teams/main/pipelines/concourse) do, for instance - and it's even the example icon we provide in [our docs](https://concourse-ci.org/resources.html#schema.resource.icon)), so this change will result in a lot of broken pipeline icons.

@vito should we hold off on merging this?

**Comment by vito** [comment]
@aoldershaw I think it's fine. We'll just need to include it in the release notes and update the places that use it.

**Comment by pnsantos** [comment]
release note added :+1:

**Pull request merged**
