### PR TITLE
add support for archiving pipelines

### PR DESCRIPTION
**Pull request by tkellen**
adds functionality in fly and api for archiving and unarchiving
pipelines, in support of gh-2518.

replicates:
concourse/go-concourse#17
concourse/fly#258
concourse/atc#300

### CODE REVIEW

**Comment by tkellen** [comment]
Heads up there are some failing tests in ATC related to counterfeiter I haven't looked at yet.

**Comment by tkellen** [comment]
Hi @vito! I don't currently have the time to take the implementation all the way through to the UI. 

Assuming there is any interest within the Concourse team (or community) to complete that part of the work I would be happy to clean up this PR and get the cli/backend/api layer ready.

Let me know what you think!

**Comment by vito** [comment]
@tkellen Sure! I can put this in the UX backlog once the backend is ready. :+1:

**Comment by tkellen** [comment]
Apologies for dropping off the map with this. I wound up resolving this by entirely deleting branch pipelines after the associated branch/pr was closed. Turns out the build history isn't as important as I originally imagined.

**Comment by vito** [comment]
@tkellen Hey, no worries and thanks for circling back! Interestingly, the need for this sort of thing came up naturally in our march towards the semi-jokingly-named [v10 roadmap](https://blog.concourse-ci.org/core-roadmap-towards-v10/). I've got an up-to-date proposal on how pipeline archiving can work and integrate with other parts of the roadmap in [RFC #33](https://github.com/concourse/rfcs/pull/33) ([Rendered](https://github.com/vito/rfcs/blob/archiving/033-archiving-pipelines/proposal.md)). I'd be interested in hearing if this proposal aligns with what you originally wanted out of pipeline archiving.

Since this is on our roadmap now, we're prepared to work on it soon ourselves. So if you no longer have the time to keep working on this, feel free to just close out the PR. But if you're interested and *do* have the time, we'd be more than happy to help from a design/code review(/pairing?) standpoint. This way we can speed up the roadmap even more by working on other things too. :slightly_smiling_face: Either one is perfectly fine!

**Comment by tkellen** [comment]
Hey @vito--I just read through the "v10" roadmap. Dunno how I missed that. Holy hell man! You've hit on almost everything I've been trying (pretty successfully) to automate away with dynamically generated (and deleted pipelines). I'd really like to pair with you and show you what I've been working on to see what ideas the conversation parks.

I also think it'd be fun to pair with someone on a rebase of this work just to get us back to the place where what I originally implemented is useable in the current codebase. Once that is done I think I'd step back and let ya'll take it from there.

I'll get back on discourse next week and see if we can coordinate some of this there!

**Comment by vito** [comment]
Closing as this is now being implemented! :) Project: http://project.concourse-ci.org/projects/MDc6UHJvamVjdDM4Mzc3ODI=

https://github.com/concourse/concourse/pull/5387 I believe is analogous to the work that was done in this PR so far. That's been merged, and now we're moving on to the UI work and automated archiving. up next.

**Comment by tkellen** [comment]
:tada: thank you!

**Pull request closed without merging**
