### PR TITLE
Restrict names by [0-9a-z-] when saving pipeline config 

### PR DESCRIPTION
**Pull request by xtremerui**
names of pipeline, group, resource, resource type, job, get plan, put plan
and task plan are restricted to lower case alphanumeric and '-'

implements https://github.com/concourse/concourse/issues/3985

### CODE REVIEW

**Comment by robwhitby** [comment]
Hi, 

I'm not in favour of this change for a couple of reasons. 

We have over 1000 pipelines that will have to be updated - which is a pain in itself, but after doing that a lot of jobs will lose their build history because the name has changed. 

Also our users like to use human readable names for jobs and especially tasks. e.g. `Deploy to Dev (onprem)`, `Run Tests` etc. etc. It helps make the pipeline understandable in the UI.

Maybe the restriction could be made a warning instead of an error? or the set of allowed characters expanded?

Thanks

**Comment by xtremerui** [comment]
@robwhitby do you mind also add your comment to the original issue so folks can discuss more about it there? Certainly there are others who will share you thoughts as well. We could find a feasible way.

Thx!

**Comment by clarafu** [comment]
This PR is basically only going to restrict users from setting new or existing pipelines from using anything other than lower case alphanumeric and dashes but it doesn't deal with existing untouched pipelines. @vito Are we going to strategize for how we are going to deal with converting existing pipelines with illegal names within the hierarchical pipelines issue?

**Comment by cirocosta** [comment]
https://github.com/concourse/rfcs/pull/40

**Comment by vito** [comment]
Let's put this down until concourse/rfcs#40 is resolved. 👍

**Pull request closed without merging**
