### PR TITLE
`fly pin-resource` requires a version if the resource is unpinned

### LINKED ISSUE #6094: fly pin-resource fails without error
## Summary

Attempting to pin a resource via the concourse UI is successful.  
Using the fly cli though, I am not able to 

## Steps to reproduce
1. Attempt to pin a resource with the CLI 
2. Observe it does not work
3. Observe it does work if pinned via UI
```
➜  concourse git:(master) ✗ fly -t zc-carsharing-dev pin-resource -r scott/deployment-manifests
➜  concourse git:(master) ✗
➜  concourse git:(master) ✗ fly -t zc-carsharing-dev resources -p scott
name                  type  pinned
deployment-manifests  git   n/a
```

## Expected results
Resource is pinned

## Actual results

Resource is not pinned, operation is a no-op
I didn't see anything in the logs at all really when tailing the logs while attempting this operation

## Triaging info

* Concourse version: v6.5.1
* Did this used to work? didn't work on 5.x either

### PR DESCRIPTION
**Pull request by jamieklassen**
[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

## What does this PR accomplish?

**Bug Fix** | Feature | Documentation

closes #6094.

## Changes proposed by this PR:

add the `required` struct tag to the `Version` field, and an integration test -- just in case we ever change flag libraries.

## Release Note

Previously, you could run the command on an unpinned resource without passing a version -- it would run and succeed, but do nothing. Now the command will fail and print an error message.

## Contributor Checklist

- [x] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [x] [Signed] all commits
- [x] Added tests (Unit and/or Integration)
- [x] ~Updated [Documentation]~
- [x] Added release note (Optional)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist

- [x] Code reviewed
- [x] Tests reviewed
- [x] ~Documentation reviewed~
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [x] ~New config flags added? Ensure that they are added to the [BOSH](https://github.com/concourse/concourse-bosh-release) and [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for the [integration tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env) (for example, if they are Garden configs that are not displayed in the `--help` text).~

### CODE REVIEW

**Review by zoetian — APPROVED** [review]
✅  LGTM! 

**Cough Cough** this is wayyy to early

**Review by zoetian — CHANGES_REQUESTED** [review]
Looks like we still need to fix some of the integration tests on pinning resources with specific version here: https://github.com/concourse/concourse/blob/master/fly/integration/pin_resource_test.go#L191
and https://github.com/concourse/concourse/blob/master/fly/integration/pin_resource_test.go#L212

**Comment by jamieklassen** [comment]
This is a bit trickier than I thought. I'm interested mainly in these two scenarios:

* `-r` is provided, the resource exists, and it is not currently pinned - this means `-v` is required.
* `-r` is provided, the resource exists and it is currently pinned - then `-v` is optional, which allows modifying the comment independent of the version.

In any case, this means that adding a `required` struct tag is not gonna work!

**Comment by jamieklassen** [comment]
@jomsie you've got it! That 'pin first, comment later' workflow is exactly the one I had to accomodate in my rewrite of this PR.

**Comment by jomsie** [comment]
@jamieklassen well then I have no more confusion or hesitation!

**Review by jomsie — APPROVED** [review]

**Pull request merged**
