### PR TITLE
change migrations timestamp to avoid upgrade issues ( CI: skip-migrations-check )

### LINKED ISSUE #7753: "pq: column p.paused_by does not exist" after upgrade from v7.4.1 to v7.6.0
### Discussed in https://github.com/concourse/concourse/discussions/7746

<div type='discussions-op-text'>

<sup>Originally posted by **coffee-squirrel** October 29, 2021</sup>
We've just upgraded (using `concourse-bosh-deployment`) a sandbox environment from Concourse v7.4.1 to v7.6.0 (skipping [v7.5.0](https://github.com/concourse/concourse/releases/tag/v7.5.0) to let things settle per the release notes), and are now seeing the dreaded "experiencing turbulence" page.  We have a stable pipeline in place to generate the manifest, do the `bosh deploy`, etc., which completed successfully for this upgrade, so I don't believe there were any issues with that part.

Specifically, I see the `/api/v1/jobs` and `/api/v1/pipelines` endpoints are returning HTTP 500 (although others, e.g. `/api/v1/resources` and `/api/v1/teams`, are fine, I can log in, etc.).

Looking at `/var/vcap/sys/log/web/web.stdout.log`, I see messages (not the `j.` and `p.` variants) like:
```
{"timestamp":"2021-10-29T13:38:13.199619750Z","level":"error","source":"atc","message":"atc.list-all-pipelines.failed-to-get-all-visible-pipelines","data":{"error":"pq: column p.paused_by does not exist","session":"4989"}}
{"timestamp":"2021-10-29T13:38:13.202180818Z","level":"error","source":"atc","message":"atc.list-all-jobs.failed-to-get-all-visible-jobs","data":{"error":"pq: column j.paused_by does not exist","session":"4991"}}
{"timestamp":"2021-10-29T13:38:13.433912798Z","level":"error","source":"atc","message":"atc.list-all-pipelines.failed-to-get-all-visible-pipelines","data":{"error":"pq: column p.paused_by does not exist","session":"5001"}}
{"timestamp":"2021-10-29T13:38:13.436061651Z","level":"error","source":"atc","message":"atc.list-all-jobs.failed-to-get-all-visible-jobs","data":{"error":"pq: column j.paused_by does not exist","session":"5003"}}
{"timestamp":"2021-10-29T13:38:18.439648476Z","level":"error","source":"atc","message":"atc.list-all-pipelines.failed-to-get-all-visible-pipelines","data":{"error":"pq: column p.paused_by does not exist","session":"5013"}}
{"timestamp":"2021-10-29T13:38:18.459025911Z","level":"error","source":"atc","message":"atc.list-all-jobs.failed-to-get-all-visible-jobs","data":{"error":"pq: column j.paused_by does not exist","session":"5015"}}
{"timestamp":"2021-10-29T13:38:18.561999961Z","level":"error","source":"atc","message":"atc.list-all-pipelines.failed-to-get-all-visible-pipelines","data":{"error":"pq: column p.paused_by does not exist","session":"5025"}}
{"timestamp":"2021-10-29T13:38:18.565321897Z","level":"error","source":"atc","message":"atc.list-all-jobs.failed-to-get-all-visible-jobs","data":{"error":"pq: column j.paused_by does not exist","session":"5028"}}
{"timestamp":"2021-10-29T13:38:22.053735576Z","level":"error","source":"atc","message":"atc.scheduler.tick.component-failed","data":{"error":"find jobs to schedule: pq: column j.paused_by does not exist","session":"26.96"}}
{"timestamp":"2021-10-29T13:38:22.196083663Z","level":"error","source":"atc","message":"atc.reaper.tick.build-reaper.failed-to-get-pipelines","data":{"error":"pq: column p.paused_by does not exist","session":"28.96.2"}}
```

I've recreated the `web` instance (`bosh recreate web`), but the issue persists.

Looking at https://github.com/concourse/concourse/search?q=%22paused_by%22&type=code , it seems like there should've been a DB migration that happened but didn't (given the error messages).  183ce5e8298b79e61fcdbd450077ae5897d4c671 (#7273) indicates `paused_by` was introduced in `v7.5.0`.

```
Name       Release(s)                     Stemcell(s)                                    Team(s)
concourse  backup-and-restore-sdk/1.18.9  bosh-vsphere-esxi-ubuntu-bionic-go_agent/1.36  -
           bpm/1.1.15
           concourse/7.6.0
           os-conf/19
           postgres/43
```

As this is a sandbox environment we're not overly concerned, but it's definitely going to make us stick to v7.4.1 for a while longer in our Prod environment.

Would anyone happen to have a suggestion on how to proceed?</div>

Comment confirming the issue is 7.5.0 migrations are skipped: https://github.com/concourse/concourse/discussions/7746#discussioncomment-1559797

### PR DESCRIPTION
**Pull request by muntac**
## Changes proposed by this PR

closes #7753

The timestamp on these migrations are later than some migrations on 7.5 and 7.6. This means those migrations won't run if these don't have an earlier timestamp.

* [x] change timestamp of latest 7.4.x specific migrations on to a time earlier than the earliest timestamp on 7.5 

## Notes to Reviewer

The migration in concern here is `drop_build_event_id_seq`.

Original timestamps:
Screen Shot 2021-11-01 at 3 13 03 PM

Modified timestamps
Screen Shot 2021-11-01 at 3 12 47 PM

Reduced `1627322257` to smallest value after `1625844436`. 

## Release Note

* Change timestamp of backported DB migration to avoid skipping any migrations when upgrading to 7.5 and later versions.
  * If you are on `7.4.1` or `7.4.2` then downgrade back to `7.4.0` using backups you have or the `concourse migrate` command, using the `7.4.1`/`7.4.2` version of the binary to downgrade back to 7.4.0. The `7.4.0` database version is `
1625844436`. Then you can safely upgrade directly to 7.4.3 or any later version of Concourse

### CODE REVIEW

**Comment by muntac** [comment]
Migrations check is failing. Recommendation was to add `skip-migrations-check` to the title. But can't get the `concourse-pr` resource to pick it up despite clearing the resource cache.

**Review by taylorsilva — COMMENTED** [review]
So this will fix the upgrade path for anyone that does the following:
```
6.7.x -> 7.4.3 (only this version) -> some post-7.6.x version
```
Correct?

Then the solution for anyone that did upgrade to `7.4.1` or `7.4.2` is to downgrade back to whatever version they came from and go right to 7.4.3 or 7.5.x/7.6.x? They can use the `concourse migrate` command if they want to manually manage that instead of using backups.

**Review by taylorsilva — COMMENTED** [review]
This same migration is in 7.5.0/7.6.0 right? Is it safe to run twice?

Answering my own question, I think it is. It only tries to drop the sequence if it exists.
https://github.com/concourse/concourse/blob/e3d9f5bb1d41e56b5de584e2b96505a90f1fe2b6/atc/db/migration/migrations/1630515499_drop_build_event_id_seq.up.sql#L9

**Review by taylorsilva — APPROVED** [review]
All my concerns have been answered. I think this is good to go 👍

**Comment by jmccann** [comment]
Was wondering if anyone could post some notes to https://github.com/concourse/concourse/discussions/8298 regarding how to upgrade from 7.4.3 to 7.7.1 with these DB migrations in mind.

**Pull request merged**
