### PR TITLE
Added cf-cli-resource

### PR DESCRIPTION
**Pull request by patrickcrocker**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@patrickcrocker Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/concourse&pullRequestId=1039)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/concourse&pullRequestId=1039) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by patrickcrocker** [comment]
cla signed!

**Comment by pivotal-issuemaster** [comment]
@patrickcrocker Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/concourse&pullRequestId=1039)!

**Comment by joshzarrabi** [comment]
Looks good, thanks!

**Pull request merged**
