### PR TITLE
add configuration for Microsoft login

### PR DESCRIPTION
**Pull request by AnianZ**
# Why do we need this PR?
I noticed that the icon for a Microsoft Login was already there and [dex supports it](https://github.com/dexidp/dex/blob/master/Documentation/connectors/microsoft.md) but there was no dedicated way to configure it in concourse. I want to configure my concourse instance to allow a Microsoft Login as well and thought enabling this configuration option would be a good way to contribute back to the project.
 

# Changes proposed in this pull request
* Enable configuring login via Microsoft in the skymarshal setup using the dex Microsoft connector

# Contributor Checklist
- [ ] Unit tests -> _None of the other connectors have them. Should I include one anyway? I'm happy to add one if needed_
- [ ] Updated documentation (located at https://github.com/concourse/docs) -> _PR in the works and will be linked shortly. Until then the dex docs also specify all necessary flags_
- [x] Updated release notes (located at https://github.com/concourse/concourse/tree/master/release-notes)

# Reviewer Checklist
- [x] Code reviewed
- [x] Tests reviewed
- [ ] Documentation reviewed
- [x] Release notes reviewed
- [ ] PR acceptance performed

### CODE REVIEW

**Comment by deniseyu** [comment]
@AnianZ to your question about unit tests: we've found it too clunky to write automated tests for dev providers, so don't worry about this as part of this PR. thanks for checking!
v5.7.0 went out today so I'll port your release notes to the next release branch.

**Comment by xtremerui** [comment]
@AnianZ we do have some [unit tests](https://github.com/concourse/concourse/blob/ee6730b995688e0f7ce902a607a9b01c8bf16b0d/fly/integration/set_team_test.go#L102) at least for `fly set-team --config`. Could you add one for microsoft connector too?

**Comment by xtremerui** [comment]
Also just a reminder that we need:
- [ ] update cocnourse-bosh-release to include the new flags for main team
- [ ] update [docs](https://concourse-ci.org/configuring-auth.html) to have a page of microsoft auth

**Comment by deniseyu** [comment]
hey @AnianZ, let us know if you need any support with adding docs and/or the unit test that @xtremerui suggested!

**Comment by AnianZ** [comment]
Hi @deniseyu, sorry for responding earlier. I did this PR when I had more time on my hands and the last two weeks were a lot busier. But I hope to add the tests and docs this weekend. The docs are already mostly done but I did not look at the tests yet.

**Comment by deniseyu** [comment]
In the interest of getting this out before too much context-switching penalty is incurred, we're going to go ahead and merge this for v5.8.0. @AnianZ if you have time later on, unit tests would be welcome! I'll have a go at writing some docs and will tag you a PR over there, feel free to weigh in if you have time as well.

**Pull request merged**
