### PR TITLE
fly: remove "better go catch it lol"

### PR DESCRIPTION
**Pull request by gdamjan**
I guess the pun was fun when it was originally added, but seeing it more than once (also when you're angry) is annoying.

Let's just remove the pun and be more serious.

### CODE REVIEW

**Comment by marco-m** [comment]
I disagree with this PR. That pun is part of Concourse and I like it.

**Comment by gdamjan** [comment]
YMMV, but it sounds really unprofessional and condescending to its users (and probably when they least need it)

**Comment by jtarchie** [comment]
I believe that this reflects on a moment of nostalgia for most in the Concourse community. As a member who has been using concourse for a long time, this was subtle and smirking pun. Quick, witty, and unexpected. A moment to reflect, don't take things (too) seriously, you'll get through them.

There's a precedent for applications to have their own humour. This can be attributed to easter eggs, humorous 404 pages, etc. A personal favorite is the Konami code.

Every new user I've paired with in concourse has appreciated the joke. As at some point, for them, it is an error message.

I'm in the position to keep it. I like it.

**Comment by xtremerui** [comment]
Have we settled to an agreement here? Could I close this PR @gdamjan ?

**Comment by gdamjan** [comment]
> Have we settled to an agreement here? Could I close this PR @gdamjan ?

it seems *you* have an agreement, I personally don't find the argument "it's part of concourse" really convincing. But I should've expected this backlash when trying to change in-group jokes.

I wonder if I opened a PR adding jokes if that would be more part of concourse???

**Pull request closed without merging**
