### PR TITLE
[#4150] closing zstd buffers to prevent leak

### PR DESCRIPTION
**Pull request by kcmannem**

### CODE REVIEW

**Comment by cirocosta** [comment]
https://github.com/concourse/baggageclaim/pull/27 just got in 😁  

If you'd like to get this one into `hush-house` today, just let me know! 😁

**Comment by kcmannem** [comment]
@cirocosta I'm thinking of letting it sit on prod over the weekend, and then go onto hush-house on Monday? Or do you think its a good idea to have them on both?

**Comment by kcmannem** [comment]
can we merge this in and have another pr which bumps baggageclaim?

**Comment by cirocosta** [comment]
> @cirocosta I'm thinking of letting it sit on prod over the weekend, and then go onto hush-house on Monday? Or do you think its a good idea to have them on both?

I'm fairly confident with having both 😁  on you then 😁

**Comment by ddadlani** [comment]
@kmannem sure but won't there still be a leak then? until baggageclaim gets bumped

**Comment by ddadlani** [comment]
just bumped baggageclaim, we'll wait on that so the entire fix gets in at once

**Comment by kcmannem** [comment]
ty

**Pull request merged**
