### PR TITLE
WIP: Fix #3855

### LINKED ISSUE #3855: It's difficult to set oidc users
## What challenge are you facing?
related: https://github.com/concourse/concourse/pull/3402#issuecomment-487287372

OIDC users are set by the subject claim, but this value cannot be got without passing through the oidc client.
So, It's difficult to set the oidc users for operators.

## What would make this better?
If there is no problem even if `CONCOURSE_OIDC_USER_ID_KEY` is set, it is easy.

## Are you interested in implementing this yourself?
Yes.

### PR DESCRIPTION
**Pull request by cappyzawa**
fix #3855 

blocked by https://github.com/concourse/dex/pull/8 or https://github.com/dexidp/dex/pull/1448

### CODE REVIEW

**Comment by cappyzawa** [comment]
@vito https://github.com/dexidp/dex/pull/1448 is merged 🎉 

What should I do to merge this change into concourse/dex ?

**Comment by cirocosta** [comment]
Hi @cappyzawa , thanks for the PR!

cc @pivotal-jwinters

**Comment by pivotal-jwinters** [comment]
I'm actually a little hesitant to make this change (even though dex accepted the PR).

OIDC is a standard, that says the `sub` is the unique identifier for the user. The reason we made the `user_id` configurable in the OAuth connector is because there is no standard claim to identify the user.

In addition, what you are actually trying to achieve is a better way to identity the user, when doing set-team, so that you don't have to use some guid, is that correct? You can already do this by specifying the username, [which already is configurable](https://github.com/concourse/concourse/blob/master/skymarshal/skycmd/oidc_flags.go#L27).

**Comment by cappyzawa** [comment]
@pivotal-jwinters Oh... I misunderstood that user name key is only related to the display of UI 🤦

Now, I try to login with `CONCOURSE_OIDC_USER_NAME_KEY`, then succeed.
Thanks for your useful information :bow:

@cirocosta Thanks!!

**Pull request closed without merging**
