### PR TITLE
Add pointer to PyPI Packages resource.

### PR DESCRIPTION
**Pull request by mboldt**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mboldt Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/concourse&pullRequestId=809) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by mboldt** [comment]
I'm a Pivot...CLA shouldn't be a problem.

**Comment by vito** [comment]
you should be able to sign as an organization then

**Comment by pivotal-issuemaster** [comment]
@mboldt Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/concourse&pullRequestId=809)!

**Comment by vito** [comment]
thanks!

**Pull request merged**
