### PR TITLE
atc: refactor customize role mappings

### PR DESCRIPTION
**Pull request by pivotal-jwinters**
This PR is simply a refactor of customizing role mappings.

### CODE REVIEW

**Comment by xtremerui** [comment]
With the move of `CustomizeActionRoleMap` from accessor to command.go, the test is gone in accessor_test as well. Is it possible to have the test still? Or how should we cover the test of `parseCustomRoles` in command.go now?

**Comment by pivotal-jwinters** [comment]
This is just configuration, so i wasn't planning on testing it. I could maybe add a test under `atc/integration` though.

**Comment by pivotal-jwinters** [comment]
@xtremerui I added an integration test for the customization logic

**Comment by hristorikev** [comment]
Hi @jwntrs , @xtremerui Did you test the change with the bosh Concourse? As I'm currently trying to setup RBAC with a BOSH deployed Concourse and I'm getting:

```
error: invalid argument for flag `--config-rbac' (expected flag.File): stat member:/var/vcap/jobs/web/config/env/CONCOURSE_CONFIG_RBAC_member,owner:/var/vcap/jobs/web/config/env/CONCOURSE_CONFIG_RBAC_owner: no such file or directory
```

More details here https://github.com/concourse/concourse/discussions/7779

**Pull request merged**
