### PR TITLE
Add Honeycomb.io as optional tracing backend

### PR DESCRIPTION
**Pull request by spire-allyjweir**
[imperative mood]: https://chris.beams.io/posts/git-commit/#imperative

## What does this PR accomplish?

Feature

Since tracing was added as an experimental feature, I have been keen to bring that data into Honeycomb for analysis alongside the rest of our observability data. Given that Concourse already had support for one proprietary vendor (Stacktrace), I added Honeycomb's exporter as an additional configurable option.
## Changes proposed by this PR:

* Add Honeycomb.io OpenTelemetry exporter as optional tracing backend to compliment existing Jaeger and Stackdriver options.
    * The foundations laid by previous maintainers made it very easy to extend and add the new exporter as a configurable option. I pinned the version of the exporter I used at `v0.2.1` to match that of the existing exporters and OTel library in use within Concourse.

## Notes to reviewer:

To test this, you can sign up for a free Honeycomb account here: https://ui.honeycomb.io/signup

Once you've signed up for the site, you will be directed to create a 'dataset' and will be provided with an API key. Take note of this as you can use it when configuring Honeycomb with Concourse.

To configure Concourse running locally using the `docker-compose.yml` in the repository to use the Honeycomb tracing exporter, add the following configuration to the `services.web.environment` object in the YAML:

```yaml
      CONCOURSE_TRACING_HONEYCOMB_API_KEY: "[API_KEY_HERE]" 
      CONCOURSE_TRACING_HONEYCOMB_DATASET: "[DATASET_NAME_HERE]"

      # This is optional. As noted in the changeset, this defaults to `concourse`
      CONCOURSE_TRACING_HONEYCOMB_SERVICE_NAME: "my-local-test-concourse"
```
## Contributor Checklist

- [X] Followed [Code of conduct], [Contributing Guide] & avoided [Anti-patterns]
- [X] [Signed] all commits
- [X] Updated [Documentation] (see https://github.com/concourse/docs/pull/373)
- [ ] Added tests (Unit and/or Integration) - *No tests added as neither Jaeger or Stackdriver had any.*
- [ ] Added release note (Optional)

[Code of Conduct]: https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md
[Contributing Guide]: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md
[Anti-patterns]: https://github.com/concourse/concourse/wiki/Anti-Patterns
[Signed]: https://help.github.com/en/github/authenticating-to-github/signing-commits
[Documentation]: https://github.com/concourse/docs

## Reviewer Checklist

- [ ] Code reviewed
- [ ] Tests reviewed
- [ ] Documentation reviewed
- [ ] Release notes reviewed
- [ ] PR acceptance performed
- [ ] New config flags added? Ensure that they are added to the
  [BOSH](https://github.com/concourse/concourse-bosh-release) and
  [Helm](https://github.com/concourse/helm) packaging; otherwise, ignored for
  the [integration
  tests](https://github.com/concourse/ci/tree/master/tasks/scripts/check-distribution-env)
  (for example, if they are Garden configs that are not displayed in the
  `--help` text).

### CODE REVIEW

**Comment by spire-allyjweir** [comment]
[This PR](https://github.com/concourse/concourse/pull/6106) from @christophermancini updates otel dependencies to a later version. I explicitly didn't address this in my PR (as mentioned in the original description) but would be happy to wait for it to be merged then rework this PR to use a more up-to-date version of the Honeycomb exporter.

**Comment by christophermancini** [comment]
> [This PR](https://github.com/concourse/concourse/pull/6106) from @christophermancini updates otel dependencies to a later version. I explicitly didn't address this in my PR (as mentioned in the original description) but would be happy to wait for it to be merged then rework this PR to use a more up-to-date version of the Honeycomb exporter.

#6106 was merged!

**Review by chenbh — COMMENTED** [review]
Thanks for this! It was super easy to setup and a quick check showed all the spans I expected to see.

Do you mind updating the Release Note section to include the configuration options? Once that and the merge conflicts are resolved I think this is good to go.

**Comment by chenbh** [comment]
Btw, I'm also playing around with https://github.com/concourse/concourse/pull/6122 by setting up a sidecar OTLP collector and using the [community exporters](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/exporter). This way the collector can receive events from Concourse via OTLP and re-publish them in any of the other community supported exporters.

Happy to accept this PR, just making a note here in case anybody needs a new backend and doesn't mind running a sidecar/agent/collector.

**Comment by spire-allyjweir** [comment]
Hi @chenbh, yep the OTLP collector is another good way to approach this problem in a more generic way for any community exporter. I _think_ that the OLTP collector could be used without modification if the Jaeger tracing backend in Concourse already. Not 100% sure as I've not actively played with it yet.

Thanks for still considering merging this PR. I think having exporters integrated directly will make the onboarding experience quite a bit easier for newcomers to collecting observability data from Concourse.

**Review by chenbh — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
